<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Cyp2c50 – DMET results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Cyp2c9.html" rel="next">
<link href="./Cyp2c39.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ATPase.html">Protein Analyses</a></li><li class="breadcrumb-item"><a href="./Cyp2c50.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Cyp2c50</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DMET results</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Results overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis progress</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./credible_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Credible intervals</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Protein Analyses</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ATPase.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">ATPase</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Abcb4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Abcb4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bcrp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bcrp</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bsep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bsep</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ces1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Ces1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp1a2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Cyp1a2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c29.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cyp2c29</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c39.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cyp2c39</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c50.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Cyp2c50</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Cyp2c9</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2d10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Cyp2d10</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2d26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Cyp2d26</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2d9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cyp2d9</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2e1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Cyp2e1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2f2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cyp2f2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp3a11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cyp3a11</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ent1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ent1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mrp2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mrp2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mrp3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Mrp3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ntcp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ntcp</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Oatp1a4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Oatp1a4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Oatp2a1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Oatp2a1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Oct1.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Oct1.2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ugt1a1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Ugt1a1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ugt1a6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Ugt1a6</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ugt2a2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Ugt2a2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#protein-overview" id="toc-protein-overview" class="nav-link active" data-scroll-target="#protein-overview"><span class="header-section-number">10</span> Protein Overview</a></li>
  <li><a href="#data-and-normalization" id="toc-data-and-normalization" class="nav-link" data-scroll-target="#data-and-normalization"><span class="header-section-number">11</span> Data and normalization</a>
  <ul class="collapse">
  <li><a href="#heritability" id="toc-heritability" class="nav-link" data-scroll-target="#heritability"><span class="header-section-number">11.1</span> Heritability</a></li>
  </ul></li>
  <li><a href="#pqtl-genome-scan" id="toc-pqtl-genome-scan" class="nav-link" data-scroll-target="#pqtl-genome-scan"><span class="header-section-number">12</span> pQTL genome scan</a></li>
  <li><a href="#significant-peaks" id="toc-significant-peaks" class="nav-link" data-scroll-target="#significant-peaks"><span class="header-section-number">13</span> Significant peak(s)</a>
  <ul class="collapse">
  <li><a href="#chromosome-19-peak-unc30282360" id="toc-chromosome-19-peak-unc30282360" class="nav-link" data-scroll-target="#chromosome-19-peak-unc30282360"><span class="header-section-number">13.1</span> Chromosome 19 peak (UNC30282360)</a>
  <ul class="collapse">
  <li><a href="#merge-diplotype-fine-mapping" id="toc-merge-diplotype-fine-mapping" class="nav-link" data-scroll-target="#merge-diplotype-fine-mapping"><span class="header-section-number">13.1.1</span> Merge / diplotype fine-mapping</a></li>
  <li><a href="#timbr-allelic-series" id="toc-timbr-allelic-series" class="nav-link" data-scroll-target="#timbr-allelic-series"><span class="header-section-number">13.1.2</span> TIMBR allelic series</a></li>
  <li><a href="#rna-mediation" id="toc-rna-mediation" class="nav-link" data-scroll-target="#rna-mediation"><span class="header-section-number">13.1.3</span> RNA mediation</a></li>
  </ul></li>
  <li><a href="#chromosome-3-peak-unc5366241" id="toc-chromosome-3-peak-unc5366241" class="nav-link" data-scroll-target="#chromosome-3-peak-unc5366241"><span class="header-section-number">13.2</span> Chromosome 3 peak (UNC5366241)</a>
  <ul class="collapse">
  <li><a href="#merge-diplotype-fine-mapping-1" id="toc-merge-diplotype-fine-mapping-1" class="nav-link" data-scroll-target="#merge-diplotype-fine-mapping-1"><span class="header-section-number">13.2.1</span> Merge / diplotype fine-mapping</a></li>
  <li><a href="#timbr-allelic-series-1" id="toc-timbr-allelic-series-1" class="nav-link" data-scroll-target="#timbr-allelic-series-1"><span class="header-section-number">13.2.2</span> TIMBR allelic series</a></li>
  <li><a href="#rna-mediation-1" id="toc-rna-mediation-1" class="nav-link" data-scroll-target="#rna-mediation-1"><span class="header-section-number">13.2.3</span> RNA mediation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#zero-inflated-subset-scan" id="toc-zero-inflated-subset-scan" class="nav-link" data-scroll-target="#zero-inflated-subset-scan"><span class="header-section-number">14</span> Zero-inflated subset scan</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ATPase.html">Protein Analyses</a></li><li class="breadcrumb-item"><a href="./Cyp2c50.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Cyp2c50</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Cyp2c50</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="protein-overview" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Protein Overview</h1>
<p>Cyp2c50, also known as Cytochrome P450 2C50, is a mouse protein encoded by the gene <strong>Cyp2c50</strong>. This protein belongs to the cytochrome P450 family and plays a role in the metabolism of various compounds. The gene has several aliases, including <strong>CYP2C50</strong>, reflecting its involvement in metabolic processes in the liver and other tissues.</p>
</section>
<section id="data-and-normalization" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Data and normalization</h1>
<p>Replicate measurements were Box-Cox transformed with a protein-specific λ = <strong>0.21</strong> (95% likelihood interval 0.08 to 0.34), estimated on the individual replicates (<code>boxcox(y ~ strain)</code>, no +1 shift); because 17 replicate(s) were zero, a small shift of 796 was added before transforming. The strain phenotype is the mean of the transformed replicates and the strain noise used for the wisam weights is their variance.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/proteins/Cyp2c50_normalization.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Cyp2c50: raw replicates, Box-Cox likelihood profile and transformed replicates.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/proteins/Cyp2c50_normalization.png" download="Cyp2c50_normalization.png">PNG</a> · <a href="figures/repbc_2026-10-01/proteins/Cyp2c50_normalization.pdf" download="Cyp2c50_normalization.pdf">PDF</a></p>
</div>
<section id="heritability" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="heritability"><span class="header-section-number">11.1</span> Heritability</h2>
<p>Broad-sense heritability of the protein is <strong>0.85</strong> (95% CI 0.78–0.90; BH-adjusted P 4.53e-44). Its paired transcript is <strong>Cyp2c50 +1</strong> (array probe <code>1418653_PM_at</code>, paired from the measured peptide <code>GTNVITSLSSVLR</code>). Transcript H² is <strong>0.42</strong> (95% CI 0.24–0.56; BH-adjusted P 1.70e-08). This is a shared multi-gene probe, so the transcript signal is not gene-specific.</p>
</section>
</section>
<section id="pqtl-genome-scan" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> pQTL genome scan</h1>
<p>Genome scan of the Box-Cox phenotype with wisam weights (miqtl <code>scan.h2lmm</code>, 11 imputations); significance thresholds come from 1000 permutations (GEV fit to the permutation maxima of −log10 P). Strongest locus: chr19:37.99 Mb, P = 3.89e-13, adjusted P = 2.22e-16; 95% threshold = 4.95 (−log10 P).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_genome_scan.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Cyp2c50 genome-wide pQTL scan with the permutation threshold.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_genome_scan.pdf" download="Cyp2c50_genome_scan.pdf">PDF</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_scan_by_chromosome.pdf" download="Cyp2c50_scan_by_chromosome.pdf">PDF</a></p>
</div>
</section>
<section id="significant-peaks" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Significant peak(s)</h1>
<section id="chromosome-19-peak-unc30282360" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="chromosome-19-peak-unc30282360"><span class="header-section-number">13.1</span> Chromosome 19 peak (UNC30282360)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Peak position</th>
<th style="text-align: right;">−log10(P)</th>
<th style="text-align: right;">Adjusted P</th>
<th>90% credible interval</th>
<th>Encoding gene</th>
<th>Gene location</th>
<th>pQTL type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chr19:37.99 Mb</td>
<td style="text-align: right;">12.41</td>
<td style="text-align: right;">2.22e-16</td>
<td>37.45–48.47 Mb</td>
<td>Cyp2c50</td>
<td>chr19:40.09–40.11 Mb</td>
<td><strong>cis</strong></td>
</tr>
</tbody>
</table>
<p>A pQTL is <strong>cis</strong> when the gene encoding the protein lies within the credible interval and <strong>trans</strong> otherwise.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_scans_full_p1.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Bootstrap credible interval, chromosome 19.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_scans_full.pdf" download="Cyp2c50_ci_scans_full.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_genes_full_chr19.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Genes within the credible interval, chromosome 19 (80% interval boxed).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_genes_full_chr19.png" download="Cyp2c50_ci_genes_full_chr19.png">PNG</a></p>
</div>
<section id="merge-diplotype-fine-mapping" class="level3" data-number="13.1.1">
<h3 data-number="13.1.1" class="anchored" data-anchor-id="merge-diplotype-fine-mapping"><span class="header-section-number">13.1.1</span> Merge / diplotype fine-mapping</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mergeplot_full_UNC30282360.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Merge: SDP significance profile across the credible interval.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mergeplot_full_UNC30282360.png" download="Cyp2c50_mergeplot_full_UNC30282360.png">PNG</a></p>
</div>
<p><em>The top allelic series (SDP) from Merge is added to the book once the follow-up summary has been generated.</em></p>
</section>
<section id="timbr-allelic-series" class="level3" data-number="13.1.2">
<h3 data-number="13.1.2" class="anchored" data-anchor-id="timbr-allelic-series"><span class="header-section-number">13.1.2</span> TIMBR allelic series</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_bf_dot_chr19.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (Bayes-factor dot plot), chromosome 19; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_bf_dot_chr19.jpg" download="Cyp2c50_timbr_ci_bf_dot_chr19.jpg">JPG</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_dot_chr19.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (posterior-probability dot plot), chromosome 19; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_dot_chr19.jpg" download="Cyp2c50_timbr_ci_dot_chr19.jpg">JPG</a></p>
</div>
<p>The highest-posterior TIMBR allelic series at the peak splits the founders into <strong>allele 0</strong>: A/J, 129S1/SvImJ, NOD/ShiLtJ, NZO/HlLtJ, WSB/EiJ; <strong>allele 1</strong>: C57BL/6J, CAST/EiJ; <strong>allele 2</strong>: PWK/PhJ. That is 3 functional alleles: founders in the same group are inferred to carry the same functional allele at this locus.</p>
<p><strong>Number of functional alleles.</strong> At the lead locus (UNC30282360, 37.99 Mb) the posterior probability of a bi-allelic series (two functional alleles) is 0.14, tri-allelic 0.53, and four or more alleles 0.33; a single allele (no QTL effect) has probability 0.00. For comparison, the Chinese-restaurant-process prior gives 0.50 / 0.29 / 0.14 for one / two / three alleles, so the data move weight away from a single allele. The locus in the credible interval whose single best allelic series has the highest posterior probability is UNC30361747 (43.83 Mb; series 0,0,0,0,0,0,1,0, P = 0.71); there bi-allelic = 0.71, tri-allelic = 0.23, four or more = 0.06.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_prior_posterior_chr19.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Prior (uniform over partitions and Chinese restaurant process) versus posterior probability of the number of functional alleles at the lead and best-model loci.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_prior_posterior_chr19.png" download="Cyp2c50_allele_number_prior_posterior_chr19.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_prior_posterior_chr19.pdf" download="Cyp2c50_allele_number_prior_posterior_chr19.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_across_ci_chr19.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probability of 1, 2, 3 or 4+ functional alleles at each locus across the credible interval (dashed line: lead locus; dotted line: best-model locus).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_across_ci_chr19.png" download="Cyp2c50_allele_number_across_ci_chr19.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_across_ci_chr19.pdf" download="Cyp2c50_allele_number_across_ci_chr19.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_lead_UNC30282360_chr19.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the lead locus UNC30282360.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_lead_UNC30282360_chr19.png" download="Cyp2c50_haplotype_lead_UNC30282360_chr19.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_lead_UNC30282360_chr19.pdf" download="Cyp2c50_haplotype_lead_UNC30282360_chr19.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_best_UNC30361747_chr19.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the locus with the highest-probability allelic series, UNC30361747.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_best_UNC30361747_chr19.png" download="Cyp2c50_haplotype_best_UNC30361747_chr19.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_best_UNC30361747_chr19.pdf" download="Cyp2c50_haplotype_best_UNC30361747_chr19.pdf">PDF</a></p>
</div>
</section>
<section id="rna-mediation" class="level3" data-number="13.1.3">
<h3 data-number="13.1.3" class="anchored" data-anchor-id="rna-mediation"><span class="header-section-number">13.1.3</span> RNA mediation</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_overlay_bf_chr19_nogenes.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>RNA mediation: pQTL scan (left axis) and each candidate transcript’s best-supported model, log10 Bayes factor (right axis); transcripts with a mediation or co-local best model and log10 BF of at least 0.5 are labelled.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_overlay_bf_chr19_nogenes.png" download="Cyp2c50_mediation_overlay_bf_chr19_nogenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_overlay_bf_chr19_withgenes.png" download="Cyp2c50_mediation_overlay_bf_chr19_withgenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_bf_points_chr19.csv" download="Cyp2c50_mediation_bf_points_chr19.csv">CSV</a></p>
</div>
<p>195 candidate transcripts lie in the credible interval. <strong>29</strong> have a best-model log10 Bayes factor ≥ 0.5 with mediation or co-local as the best-supported model and are labelled in the figure (152 more reach 0.5 only for the non-mediator model and are not labelled): <strong>mediation</strong> (3): Cyp2c39 (1.49), Cyp2c38 (1.07), Cyp2c37 (0.69); <strong>co-local</strong> (26): Pik3ap1 (1.90), Slk (1.87), Cyp2c55 (1.86), Exosc1 (1.85), Nt5c2 (1.80), Pi4k2a (1.73), Pcgf6 (1.65), Tctn3 (1.58), Avpi1 (1.45), Pyroxd2 (1.41), Scd1 (1.37), Wnt8b (1.12) …. <em>Mediation</em> means the transcript is best explained as lying on the path from the QTL to the protein; <em>co-local</em> means it shares the QTL without mediating; log10 BF is the evidence for the best-supported model against the null.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Function of the 29 labelled transcripts (UniProt)">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Function of the 29 labelled transcripts (UniProt)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Function text is the UniProt (mouse) annotation retrieved on 2026-10-03; reviewed Swiss-Prot entries where available. A dash means UniProt holds no functional annotation for that symbol.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Transcript</th>
<th>Best model</th>
<th style="text-align: right;">log10 BF</th>
<th>UniProt protein</th>
<th>Function (UniProt)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Cyp2c39</em></td>
<td>mediation</td>
<td style="text-align: right;">1.49</td>
<td><a href="https://www.uniprot.org/uniprotkb/P56656">Cytochrome P450 2C39</a></td>
<td>A cytochrome P450 monooxygenase that primarily catalyzes the epoxidation of 11,12 and 14,15 double bonds of (5Z,8Z,11Z,14Z)-eicosatetraenoic acid (arachidonate) forming 11,12- and 14,15-epoxyeicosatrienoic acids (11,12- and 14,15-EET) regioisomers.</td>
</tr>
<tr class="even">
<td><em>Cyp2c38</em></td>
<td>mediation</td>
<td style="text-align: right;">1.07</td>
<td><a href="https://www.uniprot.org/uniprotkb/P56655">Cytochrome P450 2C38</a></td>
<td>A cytochrome P450 monooxygenase that primarily catalyzes the epoxidation of 11,12 double bond of (5Z,8Z,11Z,14Z)-eicosatetraenoic acid (arachidonate) forming 11,12-epoxyeicosatrienoic acid (11,12-EET) regioisomer.</td>
</tr>
<tr class="odd">
<td><em>Cyp2c37</em></td>
<td>mediation</td>
<td style="text-align: right;">0.69</td>
<td><a href="https://www.uniprot.org/uniprotkb/P56654">Cytochrome P450 2C37</a></td>
<td>A cytochrome P450 monooxygenase that metabolizes (5Z,8Z,11Z,14Z)-eicosatetraenoic acid (arachidonate) to primarily produce 12-hydroxyeicosatetraenoic acid (12-HETE). Mechanistically, uses molecular oxygen inserting one oxygen atom into a substrate, and reducing the second into a water molecule, with two electrons provided by NADPH via cytochrome P450 reductase (CPR;</td>
</tr>
<tr class="even">
<td><em>Pik3ap1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.90</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9EQ32">Phosphoinositide 3-kinase adapter protein 1</a></td>
<td>Signaling adapter that contributes to B-cell development by linking B-cell receptor (BCR) signaling to the phosphoinositide 3-kinase (PI3K)-Akt signaling pathway. Has a complementary role to the BCR coreceptor CD19, coupling BCR and PI3K activation by providing a docking site for the PI3K subunit PIK3R1.</td>
</tr>
<tr class="odd">
<td><em>Slk</em></td>
<td>co-local</td>
<td style="text-align: right;">1.87</td>
<td><a href="https://www.uniprot.org/uniprotkb/O54988">STE20-like serine/threonine-protein kinase</a></td>
<td>Mediates apoptosis and actin stress fiber dissolution</td>
</tr>
<tr class="even">
<td><em>Cyp2c55</em></td>
<td>co-local</td>
<td style="text-align: right;">1.86</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9D816">Cytochrome P450 2C55</a></td>
<td>Metabolizes arachidonic acid mainly to 19-hydroxyeicosatetraenoic acid (HETE)</td>
</tr>
<tr class="odd">
<td><em>Exosc1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.85</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DAA6">Exosome complex component CSL4</a></td>
<td>Non-catalytic component of the RNA exosome complex which has 3’-&gt;5’ exoribonuclease activity and participates in a multitude of cellular RNA processing and degradation events.</td>
</tr>
<tr class="even">
<td><em>Nt5c2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.80</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q3V1L4">Cytosolic purine 5’-nucleotidase</a></td>
<td>Broad specificity cytosolic 5’-nucleotidase that catalyzes the dephosphorylation of 6-hydroxypurine nucleoside 5’-monophosphates. In addition, possesses a phosphotransferase activity by which it can transfer a phosphate from a donor nucleoside monophosphate to an acceptor nucleoside, preferably inosine, deoxyinosine and guanosine.</td>
</tr>
<tr class="odd">
<td><em>Pi4k2a</em></td>
<td>co-local</td>
<td style="text-align: right;">1.73</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q2TBE6">Phosphatidylinositol 4-kinase type 2-alpha</a></td>
<td>Membrane-bound phosphatidylinositol-4 kinase (PI4-kinase) that catalyzes the phosphorylation of phosphatidylinositol (PI) to phosphatidylinositol 4-phosphate (PI4P), a lipid that plays important roles in endocytosis, Golgi function, protein sorting and membrane trafficking and is required for prolonged survival of neurons.</td>
</tr>
<tr class="even">
<td><em>Pcgf6</em></td>
<td>co-local</td>
<td style="text-align: right;">1.65</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q99NA9">Polycomb group RING finger protein 6</a></td>
<td>Transcriptional repressor. May modulate the levels of histone H3K4Me3 by activating KDM5D histone demethylase. Component of a Polycomb group (PcG) multiprotein PRC1-like complex, a complex class required to maintain the transcriptionally repressive state of many genes, including Hox genes, throughout development.</td>
</tr>
<tr class="odd">
<td><em>Tctn3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.58</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8R2Q6">Tectonic-3</a></td>
<td>Part of the tectonic-like complex which is required for tissue-specific ciliogenesis and may regulate ciliary membrane composition. May be involved in apoptosis regulation. Necessary for signal transduction through the sonic hedgehog (Shh) signaling pathway</td>
</tr>
<tr class="even">
<td><em>Avpi1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.45</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9D7H4">Arginine vasopressin-induced protein 1</a></td>
<td>May be involved in MAP kinase activation, epithelial sodium channel (ENaC) down-regulation and cell cycling</td>
</tr>
<tr class="odd">
<td><em>Pyroxd2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.41</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q3U4I7">Pyridine nucleotide-disulfide oxidoreductase domain-containing protein 2</a></td>
<td>Probable oxidoreductase that may play a role as regulator of mitochondrial function</td>
</tr>
<tr class="even">
<td><em>Scd1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.37</td>
<td><a href="https://www.uniprot.org/uniprotkb/P13516">Acyl-CoA desaturase 1</a></td>
<td>Stearoyl-CoA desaturase that utilizes O(2) and electrons from reduced cytochrome b5 to introduce the first double bond into saturated fatty acyl-CoA substrates. Catalyzes the insertion of a cis double bond at the Delta-9 position into fatty acyl-CoA substrates including palmitoyl-CoA and stearoyl-CoA. Gives rise to a mixture of 16:1 and 18:1 unsaturated fatty acids.</td>
</tr>
<tr class="odd">
<td><em>Wnt8b</em></td>
<td>co-local</td>
<td style="text-align: right;">1.12</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9WUD6">Protein Wnt-8b</a></td>
<td>Ligand for members of the frizzled family of seven transmembrane receptors. May play an important role in the development and differentiation of certain forebrain structures, notably the hippocampus</td>
</tr>
<tr class="even">
<td><em>Pprc1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.11</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q6NZN1">Peroxisome proliferator-activated receptor gamma coactivator-related protein 1</a></td>
<td>Acts as a coactivator during transcriptional activation of nuclear genes related to mitochondrial biogenesis and cell growth. Involved in the transcription coactivation of CREB and NRF1 target genes</td>
</tr>
<tr class="odd">
<td><em>Fnip2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.02</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80TD3">Folliculin-interacting protein 2</a></td>
<td>Binding partner of the GTPase-activating protein FLCN: involved in the cellular response to amino acid availability by regulating the non-canonical mTORC1 signaling cascade controlling the MiT/TFE factors TFEB and TFE3. Required to promote FLCN recruitment to lysosomes and interaction with Rag GTPases, leading to activation of the non-canonical mTORC1 signaling.</td>
</tr>
<tr class="even">
<td><em>Frem2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.89</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q6NVD0">FRAS1-related extracellular matrix protein 2</a></td>
<td>Extracellular matrix protein required for maintenance of the integrity of the skin epithelium and for maintenance of renal epithelia. Required for epidermal adhesion. Involved in the development of eyelids and the anterior segment of the eyeballs</td>
</tr>
<tr class="odd">
<td><em>Elovl3</em></td>
<td>co-local</td>
<td style="text-align: right;">0.85</td>
<td><a href="https://www.uniprot.org/uniprotkb/O35949">Very long chain fatty acid elongase 3</a></td>
<td>Catalyzes the first and rate-limiting reaction of the four reactions that constitute the long-chain fatty acids elongation cycle. This endoplasmic reticulum-bound enzymatic process allows the addition of 2 carbons to the chain of long- and very long-chain fatty acids (VLCFAs) per cycle.</td>
</tr>
<tr class="even">
<td><em>Pdgfc</em></td>
<td>co-local</td>
<td style="text-align: right;">0.83</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8CI19">Platelet-derived growth factor C</a></td>
<td>Growth factor that plays an essential role in the regulation of embryonic development, cell proliferation, cell migration, survival and chemotaxis. Potent mitogen and chemoattractant for cells of mesenchymal origin.</td>
</tr>
<tr class="odd">
<td><em>Poll</em></td>
<td>co-local</td>
<td style="text-align: right;">0.82</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9QXE2">DNA polymerase lambda</a></td>
<td>DNA polymerase that functions in several pathways of DNA repair. Involved in base excision repair (BER) responsible for repair of lesions that give rise to abasic (AP) sites in DNA. Also contributes to DNA double-strand break repair by non-homologous end joining and homologous recombination.</td>
</tr>
<tr class="even">
<td><em>Abcc2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.74</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8VI47">ATP-binding cassette sub-family C member 2</a></td>
<td>ATP-dependent transporter of the ATP-binding cassette (ABC) family that hydrolyzes ATP to enable active transport of substrates conjugated with glucuronate, glutathione or sulfate. Operates at apical membranes of polarized cells such as hepatocytes, renal and intestinal epithelial cells where it mediates hepatobiliary and renal excretion of conjugated substrates.</td>
</tr>
<tr class="odd">
<td><em>Sucnr1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.72</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q99MT6">Succinate receptor 1</a></td>
<td>G protein-coupled receptor for succinate able to mediate signaling through Gq/GNAQ or Gi/GNAI second messengers depending on the cell type and the processes regulated. Succinate-SUCNR1 signaling serves as a link between metabolic stress, inflammation and energy homeostasis. In macrophages, plays a range of immune-regulatory roles.</td>
</tr>
<tr class="even">
<td><em>Sfxn2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.66</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q925N2">Sideroflexin-2</a></td>
<td>Mitochondrial amino-acid transporter that mediates transport of serine into mitochondria. Involved in mitochondrial iron homeostasis by regulating heme biosynthesis</td>
</tr>
<tr class="odd">
<td><em>Nfkb2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.66</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9WTK5">Nuclear factor NF-kappa-B p100 subunit</a></td>
<td>NF-kappa-B is a pleiotropic transcription factor present in almost all cell types and is the endpoint of a series of signal transduction events that are initiated by a vast array of stimuli related to many biological processes such as inflammation, immunity, differentiation, cell growth, tumorigenesis and apoptosis.</td>
</tr>
<tr class="even">
<td><em>Cox15</em></td>
<td>co-local</td>
<td style="text-align: right;">0.65</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BJ03">Heme A synthase COX15</a></td>
<td>Catalyzes the second reaction in the biosynthesis of heme A, a prosthetic group of mitochondrial cytochrome c oxidase (CcO). Heme A is synthesized from heme B by two sequential enzymatic reactions catalyzed by heme O synthase (HOS) and heme A synthase (HAS).</td>
</tr>
<tr class="odd">
<td><em>Frat1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.58</td>
<td><a href="https://www.uniprot.org/uniprotkb/P70339">Proto-oncogene FRAT1</a></td>
<td>Positively regulates the Wnt signaling pathway by stabilizing beta-catenin through the association with GSK-3. May play a role in tumor progression and collaborate with PIM1 and MYC in lymphomagenesis</td>
</tr>
<tr class="even">
<td><em>Serp1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.55</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9Z1W5">Stress-associated endoplasmic reticulum protein 1</a></td>
<td>Interacts with target proteins during their translocation into the lumen of the endoplasmic reticulum. Protects unfolded target proteins against degradation during ER stress. May facilitate glycosylation of target proteins after termination of ER stress. May modulate the use of N-glycosylation sites on target proteins</td>
</tr>
<tr class="odd">
<td><em>Vmn2r1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.50</td>
<td><a href="https://www.uniprot.org/uniprotkb/O70410">Vomeronasal type-2 receptor 1</a></td>
<td>Putative pheromone receptor</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_posterior_bars_chr19.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probabilities of the mediation models for the strongest candidate mediator.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_targeted_mediation_chr19_posterior_bars.pdf" download="Cyp2c50_targeted_mediation_chr19_posterior_bars.pdf">PDF</a></p>
</div>
</section>
</section>
<section id="chromosome-3-peak-unc5366241" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="chromosome-3-peak-unc5366241"><span class="header-section-number">13.2</span> Chromosome 3 peak (UNC5366241)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Peak position</th>
<th style="text-align: right;">−log10(P)</th>
<th style="text-align: right;">Adjusted P</th>
<th>90% credible interval</th>
<th>Encoding gene</th>
<th>Gene location</th>
<th>pQTL type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chr3:60.51 Mb</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">5.32e-03</td>
<td>47.17–87.62 Mb</td>
<td>Cyp2c50</td>
<td>chr19:40.09–40.11 Mb</td>
<td><strong>trans</strong></td>
</tr>
</tbody>
</table>
<p>A pQTL is <strong>cis</strong> when the gene encoding the protein lies within the credible interval and <strong>trans</strong> otherwise.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_scans_full_p2.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Bootstrap credible interval, chromosome 3.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_scans_full.pdf" download="Cyp2c50_ci_scans_full.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_genes_full_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Genes within the credible interval, chromosome 3 (80% interval boxed).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_ci_genes_full_chr3.png" download="Cyp2c50_ci_genes_full_chr3.png">PNG</a></p>
</div>
<section id="merge-diplotype-fine-mapping-1" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="merge-diplotype-fine-mapping-1"><span class="header-section-number">13.2.1</span> Merge / diplotype fine-mapping</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mergeplot_full_UNC5366241.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Merge: SDP significance profile across the credible interval.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mergeplot_full_UNC5366241.png" download="Cyp2c50_mergeplot_full_UNC5366241.png">PNG</a></p>
</div>
<p><em>The top allelic series (SDP) from Merge is added to the book once the follow-up summary has been generated.</em></p>
</section>
<section id="timbr-allelic-series-1" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="timbr-allelic-series-1"><span class="header-section-number">13.2.2</span> TIMBR allelic series</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_bf_dot_chr3.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (Bayes-factor dot plot), chromosome 3; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_bf_dot_chr3.jpg" download="Cyp2c50_timbr_ci_bf_dot_chr3.jpg">JPG</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_dot_chr3.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (posterior-probability dot plot), chromosome 3; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_timbr_ci_dot_chr3.jpg" download="Cyp2c50_timbr_ci_dot_chr3.jpg">JPG</a></p>
</div>
<p>The highest-posterior TIMBR allelic series at the peak splits the founders into <strong>allele 1</strong>: C57BL/6J, 129S1/SvImJ, NOD/ShiLtJ, NZO/HlLtJ, CAST/EiJ, WSB/EiJ; <strong>allele 0</strong>: A/J, PWK/PhJ. That is 2 functional alleles: founders in the same group are inferred to carry the same functional allele at this locus.</p>
<p><strong>Number of functional alleles.</strong> At the lead locus (UNC5366241, 60.51 Mb) the posterior probability of a bi-allelic series (two functional alleles) is 0.58, tri-allelic 0.30, and four or more alleles 0.12; a single allele (no QTL effect) has probability 0.00. For comparison, the Chinese-restaurant-process prior gives 0.50 / 0.29 / 0.14 for one / two / three alleles, so the data move weight away from a single allele. The locus in the credible interval whose single best allelic series has the highest posterior probability is JAX00109064 (74.66 Mb; series 0,0,0,0,0,0,0,0, P = 0.66); there bi-allelic = 0.22, tri-allelic = 0.08, four or more = 0.04.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_prior_posterior_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Prior (uniform over partitions and Chinese restaurant process) versus posterior probability of the number of functional alleles at the lead and best-model loci.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_prior_posterior_chr3.png" download="Cyp2c50_allele_number_prior_posterior_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_prior_posterior_chr3.pdf" download="Cyp2c50_allele_number_prior_posterior_chr3.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_across_ci_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probability of 1, 2, 3 or 4+ functional alleles at each locus across the credible interval (dashed line: lead locus; dotted line: best-model locus).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_across_ci_chr3.png" download="Cyp2c50_allele_number_across_ci_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_allele_number_across_ci_chr3.pdf" download="Cyp2c50_allele_number_across_ci_chr3.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_lead_UNC5366241_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the lead locus UNC5366241.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_lead_UNC5366241_chr3.png" download="Cyp2c50_haplotype_lead_UNC5366241_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_lead_UNC5366241_chr3.pdf" download="Cyp2c50_haplotype_lead_UNC5366241_chr3.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_best_JAX00109064_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the locus with the highest-probability allelic series, JAX00109064.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_best_JAX00109064_chr3.png" download="Cyp2c50_haplotype_best_JAX00109064_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_haplotype_best_JAX00109064_chr3.pdf" download="Cyp2c50_haplotype_best_JAX00109064_chr3.pdf">PDF</a></p>
</div>
</section>
<section id="rna-mediation-1" class="level3" data-number="13.2.3">
<h3 data-number="13.2.3" class="anchored" data-anchor-id="rna-mediation-1"><span class="header-section-number">13.2.3</span> RNA mediation</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_overlay_bf_chr3_nogenes.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>RNA mediation: pQTL scan (left axis) and each candidate transcript’s best-supported model, log10 Bayes factor (right axis); transcripts with a mediation or co-local best model and log10 BF of at least 0.5 are labelled.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_overlay_bf_chr3_nogenes.png" download="Cyp2c50_mediation_overlay_bf_chr3_nogenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_overlay_bf_chr3_withgenes.png" download="Cyp2c50_mediation_overlay_bf_chr3_withgenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_bf_points_chr3.csv" download="Cyp2c50_mediation_bf_points_chr3.csv">CSV</a></p>
</div>
<p>195 candidate transcripts lie in the credible interval. <strong>48</strong> have a best-model log10 Bayes factor ≥ 0.5 with mediation or co-local as the best-supported model and are labelled in the figure (130 more reach 0.5 only for the non-mediator model and are not labelled): <strong>mediation</strong> (1): Sfxn2 (0.53); <strong>co-local</strong> (47): Fga (1.87), Med12l (1.80), 4933411K16Rik (1.79), Tiparp (1.78), Cpn1 (1.74), Ubtd1 (1.73), Commd2 (1.71), Cyp17a1 (1.69), Mfsd1 (1.66), Tmem144 (1.65), Aadac (1.59), 4930579G24Rik (1.51) …. <em>Mediation</em> means the transcript is best explained as lying on the path from the QTL to the protein; <em>co-local</em> means it shares the QTL without mediating; log10 BF is the evidence for the best-supported model against the null.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Function of the 48 labelled transcripts (UniProt)">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Function of the 48 labelled transcripts (UniProt)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Function text is the UniProt (mouse) annotation retrieved on 2026-10-03; reviewed Swiss-Prot entries where available. A dash means UniProt holds no functional annotation for that symbol.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Transcript</th>
<th>Best model</th>
<th style="text-align: right;">log10 BF</th>
<th>UniProt protein</th>
<th>Function (UniProt)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Sfxn2</em></td>
<td>mediation</td>
<td style="text-align: right;">0.53</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q925N2">Sideroflexin-2</a></td>
<td>Mitochondrial amino-acid transporter that mediates transport of serine into mitochondria. Involved in mitochondrial iron homeostasis by regulating heme biosynthesis</td>
</tr>
<tr class="even">
<td><em>Fga</em></td>
<td>co-local</td>
<td style="text-align: right;">1.87</td>
<td><a href="https://www.uniprot.org/uniprotkb/E9PV24">Fibrinogen alpha chain</a></td>
<td>Cleaved by the protease thrombin to yield monomers which, together with fibrinogen beta (FGB) and fibrinogen gamma (FGG), polymerize to form an insoluble fibrin matrix. Fibrin has a major function in hemostasis as one of the primary components of blood clots.</td>
</tr>
<tr class="odd">
<td><em>Med12l</em></td>
<td>co-local</td>
<td style="text-align: right;">1.80</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BQM9">Mediator of RNA polymerase II transcription subunit 12-like protein</a></td>
<td>May be a component of the Mediator complex, a coactivator involved in the regulated transcription of nearly all RNA polymerase II-dependent genes. Mediator functions as a bridge to convey information from gene-specific regulatory proteins to the basal RNA polymerase II transcription machinery.</td>
</tr>
<tr class="even">
<td><em>4933411K16Rik</em></td>
<td>co-local</td>
<td style="text-align: right;">1.79</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Tiparp</em></td>
<td>co-local</td>
<td style="text-align: right;">1.78</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8C1B2">Protein mono-ADP-ribosyltransferase TIPARP</a></td>
<td>ADP-ribosyltransferase that mediates mono-ADP-ribosylation of glutamate, aspartate and cysteine residues on target proteins. Acts as a negative regulator of AHR by mediating mono-ADP-ribosylation of AHR, leading to inhibit transcription activator activity of AHR (Probable)</td>
</tr>
<tr class="even">
<td><em>Cpn1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.74</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9JJN5">Carboxypeptidase N catalytic chain</a></td>
<td>Protects the body from potent vasoactive and inflammatory peptides containing C-terminal Arg or Lys (such as kinins or anaphylatoxins) which are released into the circulation</td>
</tr>
<tr class="odd">
<td><em>Ubtd1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.73</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q91WB7">Ubiquitin domain-containing protein 1</a></td>
<td>May be involved in the regulation of cellular senescence through a positive feedback loop with TP53. Is a TP53 downstream target gene that increases the stability of TP53 protein by promoting the ubiquitination and degradation of MDM2</td>
</tr>
<tr class="even">
<td><em>Commd2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.71</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BXC6">COMM domain-containing protein 2</a></td>
<td>Scaffold protein in the commander complex that is essential for endosomal recycling of transmembrane cargos; the commander complex is composed of the CCC subcomplex and the retriever subcomplex. May modulate activity of cullin-RING E3 ubiquitin ligase (CRL) complexes. May down-regulate activation of NF-kappa-B</td>
</tr>
<tr class="odd">
<td><em>Cyp17a1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.69</td>
<td><a href="https://www.uniprot.org/uniprotkb/P27786">Steroid 17-alpha-hydroxylase/17,20 lyase</a></td>
<td>A cytochrome P450 monooxygenase involved in corticoid and androgen biosynthesis. Catalyzes 17-alpha hydroxylation of C21 steroids, which is common for both pathways. A second oxidative step, required only for androgen synthesis, involves an acyl-carbon cleavage.</td>
</tr>
<tr class="even">
<td><em>Mfsd1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.66</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DC37">Lysosomal dipeptide transporter MFSD1</a></td>
<td>Lysosomal dipeptide uniporter that selectively exports lysine, arginine or histidine-containing dipeptides with a net positive charge from the lysosome lumen into the cytosol. Could play a role in a specific type of protein O-glycosylation indirectly regulating macrophages migration and tissue invasion. Also essential for liver homeostasis</td>
</tr>
<tr class="odd">
<td><em>Tmem144</em></td>
<td>co-local</td>
<td style="text-align: right;">1.65</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8VEH0">Transmembrane protein 144</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Aadac</em></td>
<td>co-local</td>
<td style="text-align: right;">1.59</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q99PG0">Deacylase AADAC</a></td>
<td>Catalyzes the hydrolysis of ester and amide bonds and is largely involved in prodrugs activation, xenobiotic detoxification or toxicity, and, in some contexts, lipid and indole metabolism. Prefers compounds with relatively small acyl groups, especially compounds with acetyl group.</td>
</tr>
<tr class="odd">
<td><em>4930579G24Rik</em></td>
<td>co-local</td>
<td style="text-align: right;">1.51</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Ppm1l</em></td>
<td>co-local</td>
<td style="text-align: right;">1.50</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BHN0">Protein phosphatase 1L</a></td>
<td>Acts as a suppressor of the SAPK signaling pathways by associating with and dephosphorylating MAP3K7/TAK1 and MAP3K5, and by attenuating the association between MAP3K7/TAK1 and MAP2K4 or MAP2K6</td>
</tr>
<tr class="odd">
<td><em>Rap2b</em></td>
<td>co-local</td>
<td style="text-align: right;">1.50</td>
<td><a href="https://www.uniprot.org/uniprotkb/P61226">Ras-related protein Rap-2b</a></td>
<td>Small GTP-binding protein which cycles between a GDP-bound inactive and a GTP-bound active form. Involved in EGFR and CHRM3 signaling pathways through stimulation of PLCE1. May play a role in cytoskeletal rearrangements and regulate cell spreading through activation of the effector TNIK. May regulate membrane vesiculation in red blood cells</td>
</tr>
<tr class="even">
<td><em>Gbf1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.49</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BWM0">Prostaglandin E synthase 2</a></td>
<td>Isomerase that catalyzes the conversion of PGH2 into the more stable prostaglandin E2 (PGE2) (in vitro). The biological function and the GSH-dependent property of PTGES2 is still under debate.</td>
</tr>
<tr class="odd">
<td><em>Mab21l2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.45</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BPP1">Protein mab-21-like 2</a></td>
<td>Required for several aspects of embryonic development including normal development of the eye, notochord, neural tube and other organ tissues, and for embryonic turning</td>
</tr>
<tr class="even">
<td><em>Pi4k2a</em></td>
<td>co-local</td>
<td style="text-align: right;">1.44</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q2TBE6">Phosphatidylinositol 4-kinase type 2-alpha</a></td>
<td>Membrane-bound phosphatidylinositol-4 kinase (PI4-kinase) that catalyzes the phosphorylation of phosphatidylinositol (PI) to phosphatidylinositol 4-phosphate (PI4P), a lipid that plays important roles in endocytosis, Golgi function, protein sorting and membrane trafficking and is required for prolonged survival of neurons.</td>
</tr>
<tr class="odd">
<td><em>Marveld1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.41</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q7TQJ1">MARVEL domain-containing protein 1</a></td>
<td>Microtubule-associated protein that exhibits cell cycle-dependent localization and can inhibit cell proliferation and migration</td>
</tr>
<tr class="even">
<td><em>Exosc8</em></td>
<td>co-local</td>
<td style="text-align: right;">1.40</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9D753">Exosome complex component RRP43</a></td>
<td>Non-catalytic component of the RNA exosome complex which has 3’-&gt;5’ exoribonuclease activity and participates in a multitude of cellular RNA processing and degradation events.</td>
</tr>
<tr class="odd">
<td><em>Tm4sf1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.39</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q64302">Transmembrane 4 L6 family member 1</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Zdhhc16</em></td>
<td>co-local</td>
<td style="text-align: right;">1.33</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9ESG8">Palmitoyltransferase ZDHHC16</a></td>
<td>Palmitoyl acyltransferase that mediates palmitoylation of proteins such as PLN and ZDHHC6. Required during embryonic heart development and cardiac function, possibly by mediating palmitoylation of PLN, thereby affecting PLN phosphorylation and homooligomerization. Also required for eye development.</td>
</tr>
<tr class="odd">
<td><em>Fbxl15</em></td>
<td>co-local</td>
<td style="text-align: right;">1.33</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q91W61">F-box/LRR-repeat protein 15</a></td>
<td>Substrate recognition component of a SCF (SKP1-CUL1-F-box protein) E3 ubiquitin-protein ligase complex which mediates the ubiquitination and subsequent proteasomal degradation of SMURF1, thereby acting as a positive regulator of the BMP signaling pathway. Required for dorsal/ventral pattern formation and bone mass maintenance. Also mediates ubiquitination of SMURF2 and WWP2</td>
</tr>
<tr class="even">
<td><em>Gfm1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.29</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8K0D5">Elongation factor G, mitochondrial</a></td>
<td>Mitochondrial GTPase that catalyzes the GTP-dependent ribosomal translocation step during translation elongation. During this step, the ribosome changes from the pre-translocational (PRE) to the post-translocational (POST) state as the newly formed A-site-bound peptidyl-tRNA and P-site-bound deacylated tRNA move to the P and E sites, respectively.</td>
</tr>
<tr class="odd">
<td><em>Arhgap19</em></td>
<td>co-local</td>
<td style="text-align: right;">1.17</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BRH3">Rho GTPase-activating protein 19</a></td>
<td>Has GTPase activator activity toward RHOA; RHOA activation results in GTP hydrolysis and conversion from an active GTP-bound to an inactive GDP-bound state. Lacks GTPase activator activity toward RAC1 or CDC42</td>
</tr>
<tr class="even">
<td><em>Ankrd2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.12</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9WV06">Ankyrin repeat domain-containing protein 2</a></td>
<td>Functions as a negative regulator of myocyte differentiation. May interact with both sarcoplasmic structural proteins and nuclear proteins to regulate gene expression during muscle development and in response to muscle stress</td>
</tr>
<tr class="odd">
<td><em>Gsto2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.12</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8K2Q2">Glutathione S-transferase omega-2</a></td>
<td>Exhibits glutathione-dependent thiol transferase activity. Has high dehydroascorbate reductase activity and may contribute to the recycling of ascorbic acid. Participates in the biotransformation of inorganic arsenic and reduces monomethylarsonic acid (MMA)</td>
</tr>
<tr class="even">
<td><em>Hps6</em></td>
<td>co-local</td>
<td style="text-align: right;">1.09</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BLY7">BLOC-2 complex member HPS6</a></td>
<td>May regulate the synthesis and function of lysosomes and of highly specialized organelles, such as melanosomes and platelet dense granules. Acts as a cargo adapter for the dynein-dynactin motor complex to mediate the transport of lysosomes from the cell periphery to the perinuclear region.</td>
</tr>
<tr class="odd">
<td><em>Glt28d2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.08</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BML3">UDP-N-acetylglucosamine transferase subunit ALG13</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>P2ry1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.96</td>
<td><a href="https://www.uniprot.org/uniprotkb/P49650">P2Y purinoceptor 1</a></td>
<td>Receptor for extracellular adenine nucleotides such as ADP. In platelets, binding to ADP leads to mobilization of intracellular calcium ions via activation of phospholipase C, a change in platelet shape, and ultimately platelet aggregation</td>
</tr>
<tr class="odd">
<td><em>Plrg1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.95</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q922V4">Pleiotropic regulator 1</a></td>
<td>Involved in pre-mRNA splicing as component of the spliceosome. Component of the PRP19-CDC5L complex that forms an integral part of the spliceosome and is required for activating pre-mRNA splicing. As a component of the minor spliceosome, involved in the splicing of U12-type introns in pre-mRNAs</td>
</tr>
<tr class="even">
<td><em>Tmem154</em></td>
<td>co-local</td>
<td style="text-align: right;">0.93</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8C4Q9">Transmembrane protein 154</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Rsrc1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.90</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DBU6">Serine/Arginine-related protein 53</a></td>
<td>Plays a role in pre-mRNA splicing. Involved in both constitutive and alternative pre-mRNA splicing. May have a role in the recognition of the 3’ splice site during the second step of splicing</td>
</tr>
<tr class="even">
<td><em>Tdo2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.89</td>
<td><a href="https://www.uniprot.org/uniprotkb/P48776">Tryptophan 2,3-dioxygenase</a></td>
<td>Heme-dependent dioxygenase that catalyzes the oxidative cleavage of the L-tryptophan (L-Trp) pyrrole ring and converts L-tryptophan to N-formyl-L-kynurenine. Catalyzes the oxidative cleavage of the indole moiety</td>
</tr>
<tr class="odd">
<td><em>Cox15</em></td>
<td>co-local</td>
<td style="text-align: right;">0.88</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BJ03">Heme A synthase COX15</a></td>
<td>Catalyzes the second reaction in the biosynthesis of heme A, a prosthetic group of mitochondrial cytochrome c oxidase (CcO). Heme A is synthesized from heme B by two sequential enzymatic reactions catalyzed by heme O synthase (HOS) and heme A synthase (HAS).</td>
</tr>
<tr class="even">
<td><em>Naa15</em></td>
<td>co-local</td>
<td style="text-align: right;">0.86</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80UM3">N-alpha-acetyltransferase 15, NatA auxiliary subunit</a></td>
<td>Auxillary subunit of N-terminal acetyltransferase complexes which display alpha (N-terminal) acetyltransferase (NAT) activity. The NAT activity may be important for vascular, hematopoietic and neuronal growth and development. Required to control retinal neovascularization in adult ocular endothelial cells.</td>
</tr>
<tr class="odd">
<td><em>Poll</em></td>
<td>co-local</td>
<td style="text-align: right;">0.82</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9QXE2">DNA polymerase lambda</a></td>
<td>DNA polymerase that functions in several pathways of DNA repair. Involved in base excision repair (BER) responsible for repair of lesions that give rise to abasic (AP) sites in DNA. Also contributes to DNA double-strand break repair by non-homologous end joining and homologous recombination.</td>
</tr>
<tr class="even">
<td><em>Dpcd</em></td>
<td>co-local</td>
<td style="text-align: right;">0.75</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BPA8">Protein DPCD</a></td>
<td>May play a role in the formation or function of ciliated cells</td>
</tr>
<tr class="odd">
<td><em>Ccnl1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.75</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q52KE7">Cyclin-L1</a></td>
<td>Regulatory component of the cyclin-L-CDK11 complex that regulates transcription and pre-mRNA splicing. Inhibited by the CDK-specific inhibitor CDKN1A/p21</td>
</tr>
<tr class="even">
<td><em>Mgst2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.74</td>
<td><a href="https://www.uniprot.org/uniprotkb/A2RST1">Microsomal glutathione S-transferase 2</a></td>
<td>Catalyzes several different glutathione-dependent reactions. Catalyzes the glutathione-dependent reduction of lipid hydroperoxides, such as 5-HPETE. Has glutathione transferase activity, toward xenobiotic electrophiles, such as 1-chloro-2, 4-dinitrobenzene (CDNB). Also catalyzes the conjugation of leukotriene A4 with reduced glutathione to form leukotriene C4 (LTC4).</td>
</tr>
<tr class="odd">
<td><em>Sucnr1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.72</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q99MT6">Succinate receptor 1</a></td>
<td>G protein-coupled receptor for succinate able to mediate signaling through Gq/GNAQ or Gi/GNAI second messengers depending on the cell type and the processes regulated. Succinate-SUCNR1 signaling serves as a link between metabolic stress, inflammation and energy homeostasis. In macrophages, plays a range of immune-regulatory roles.</td>
</tr>
<tr class="even">
<td><em>Ldb1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.68</td>
<td><a href="https://www.uniprot.org/uniprotkb/P70662">LIM domain-binding protein 1</a></td>
<td>Binds to the LIM domain of a wide variety of LIM domain-containing transcription factors. May regulate the transcriptional activity of LIM-containing proteins by determining specific partner interactions. Plays a role in the development of interneurons and motor neurons in cooperation with LHX3 and ISL1.</td>
</tr>
<tr class="odd">
<td><em>Gmps</em></td>
<td>co-local</td>
<td style="text-align: right;">0.67</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q3THK7">GMP synthase [glutamine-hydrolyzing]</a></td>
<td>Catalyzes the conversion of xanthine monophosphate (XMP) to GMP in the presence of glutamine and ATP through an adenyl-XMP intermediate</td>
</tr>
<tr class="even">
<td><em>Tm4sf4</em></td>
<td>co-local</td>
<td style="text-align: right;">0.62</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q91XD3">Transmembrane 4 L6 family member 4</a></td>
<td>Regulates the adhesive and proliferative status of intestinal epithelial cells. Can mediate density-dependent cell proliferation</td>
</tr>
<tr class="odd">
<td><em>Trpc4</em></td>
<td>co-local</td>
<td style="text-align: right;">0.61</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9QUQ5">Short transient receptor potential channel 4</a></td>
<td>Forms a receptor-activated non-selective calcium permeant cation channel. Acts as a cell-cell contact-dependent endothelial calcium entry channel. Forms a homomeric ion channel or a heteromeric ion channel with TRPC1; the heteromeric ion channel has reduced calcium permeability compared to the homomeric channel.</td>
</tr>
<tr class="even">
<td><em>As3mt</em></td>
<td>co-local</td>
<td style="text-align: right;">0.59</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q91WU5">Arsenite methyltransferase</a></td>
<td>Catalyzes the transfer of a methyl group from AdoMet to trivalent arsenicals producing methylated and dimethylated arsenicals. It methylates arsenite to form methylarsonate, Me-AsO(3)H(2), which is reduced by methylarsonate reductase to methylarsonite, Me-As(OH)2.</td>
</tr>
<tr class="odd">
<td><em>Siah2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.56</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q06986">E3 ubiquitin-protein ligase SIAH2</a></td>
<td>E3 ubiquitin-protein ligase that mediates ubiquitination and subsequent proteasomal degradation of target proteins. E3 ubiquitin ligases accept ubiquitin from an E2 ubiquitin-conjugating enzyme in the form of a thioester and then directly transfers the ubiquitin to targeted substrates.</td>
</tr>
<tr class="even">
<td><em>Lxn</em></td>
<td>co-local</td>
<td style="text-align: right;">0.50</td>
<td><a href="https://www.uniprot.org/uniprotkb/P70202">Latexin</a></td>
<td>Hardly reversible, non-competitive, and potent inhibitor of CPA1, CPA2 and CPA4. May play a role in inflammation</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_mediation_posterior_bars_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probabilities of the mediation models for the strongest candidate mediator.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_targeted_mediation_chr3_posterior_bars.pdf" download="Cyp2c50_targeted_mediation_chr3_posterior_bars.pdf">PDF</a></p>
</div>
</section>
</section>
</section>
<section id="zero-inflated-subset-scan" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Zero-inflated subset scan</h1>
<p>Cyp2c50 has strains with no detectable protein (all replicates zero). A second scan was run on the strains with measurable variation (normalized within-strain variance &gt; 0.01), re-normalized with its own Box-Cox λ, with its own permutation threshold. The binary (detected vs.&nbsp;not detected) scan has not been re-run with the new normalization.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_sub_scan.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Cyp2c50 zero-inflated subset genome scan.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp2c50/Cyp2c50_sub_scan.pdf" download="Cyp2c50_sub_scan.pdf">PDF</a></p>
</div>
<p>The subset scan has no genome-wide significant peak.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Cyp2c39.html" class="pagination-link" aria-label="Cyp2c39">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cyp2c39</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Cyp2c9.html" class="pagination-link" aria-label="Cyp2c9">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Cyp2c9</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>