<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>16&nbsp; Cyp3a11 – DMET results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ent1.html" rel="next">
<link href="./Cyp2f2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ATPase.html">Protein Analyses</a></li><li class="breadcrumb-item"><a href="./Cyp3a11.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cyp3a11</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DMET results</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Results overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis progress</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./credible_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Credible intervals</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Protein Analyses</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ATPase.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">ATPase</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Abcb4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Abcb4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bcrp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bcrp</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bsep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bsep</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ces1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Ces1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp1a2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Cyp1a2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c29.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cyp2c29</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c39.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cyp2c39</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c50.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Cyp2c50</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2c9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Cyp2c9</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2d10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Cyp2d10</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2d26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Cyp2d26</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2d9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cyp2d9</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2e1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Cyp2e1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp2f2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cyp2f2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Cyp3a11.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cyp3a11</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ent1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ent1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mrp2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mrp2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mrp3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Mrp3</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ntcp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ntcp</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Oatp1a4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Oatp1a4</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Oatp2a1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Oatp2a1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Oct1.2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Oct1.2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ugt1a1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Ugt1a1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ugt1a6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Ugt1a6</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ugt2a2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Ugt2a2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#protein-overview" id="toc-protein-overview" class="nav-link active" data-scroll-target="#protein-overview"><span class="header-section-number">17</span> Protein Overview</a></li>
  <li><a href="#data-and-normalization" id="toc-data-and-normalization" class="nav-link" data-scroll-target="#data-and-normalization"><span class="header-section-number">18</span> Data and normalization</a>
  <ul class="collapse">
  <li><a href="#heritability" id="toc-heritability" class="nav-link" data-scroll-target="#heritability"><span class="header-section-number">18.1</span> Heritability</a></li>
  </ul></li>
  <li><a href="#pqtl-genome-scan" id="toc-pqtl-genome-scan" class="nav-link" data-scroll-target="#pqtl-genome-scan"><span class="header-section-number">19</span> pQTL genome scan</a></li>
  <li><a href="#significant-peaks" id="toc-significant-peaks" class="nav-link" data-scroll-target="#significant-peaks"><span class="header-section-number">20</span> Significant peak(s)</a>
  <ul class="collapse">
  <li><a href="#chromosome-3-peak-unc5114998" id="toc-chromosome-3-peak-unc5114998" class="nav-link" data-scroll-target="#chromosome-3-peak-unc5114998"><span class="header-section-number">20.1</span> Chromosome 3 peak (UNC5114998)</a>
  <ul class="collapse">
  <li><a href="#merge-diplotype-fine-mapping" id="toc-merge-diplotype-fine-mapping" class="nav-link" data-scroll-target="#merge-diplotype-fine-mapping"><span class="header-section-number">20.1.1</span> Merge / diplotype fine-mapping</a></li>
  <li><a href="#timbr-allelic-series" id="toc-timbr-allelic-series" class="nav-link" data-scroll-target="#timbr-allelic-series"><span class="header-section-number">20.1.2</span> TIMBR allelic series</a></li>
  <li><a href="#rna-mediation" id="toc-rna-mediation" class="nav-link" data-scroll-target="#rna-mediation"><span class="header-section-number">20.1.3</span> RNA mediation</a></li>
  </ul></li>
  <li><a href="#chromosome-6-peak-unc11092470" id="toc-chromosome-6-peak-unc11092470" class="nav-link" data-scroll-target="#chromosome-6-peak-unc11092470"><span class="header-section-number">20.2</span> Chromosome 6 peak (UNC11092470)</a>
  <ul class="collapse">
  <li><a href="#merge-diplotype-fine-mapping-1" id="toc-merge-diplotype-fine-mapping-1" class="nav-link" data-scroll-target="#merge-diplotype-fine-mapping-1"><span class="header-section-number">20.2.1</span> Merge / diplotype fine-mapping</a></li>
  <li><a href="#timbr-allelic-series-1" id="toc-timbr-allelic-series-1" class="nav-link" data-scroll-target="#timbr-allelic-series-1"><span class="header-section-number">20.2.2</span> TIMBR allelic series</a></li>
  <li><a href="#rna-mediation-1" id="toc-rna-mediation-1" class="nav-link" data-scroll-target="#rna-mediation-1"><span class="header-section-number">20.2.3</span> RNA mediation</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ATPase.html">Protein Analyses</a></li><li class="breadcrumb-item"><a href="./Cyp3a11.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cyp3a11</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cyp3a11</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="protein-overview" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Protein Overview</h1>
<p>The mouse protein Cyp3a11, also known as Cytochrome P450 3A11, is encoded by the gene <strong>Cyp3a11</strong>. It is involved in the metabolism of various drugs and xenobiotics. The protein has several aliases, including <strong>Cyp3a</strong> and <strong>Cytochrome P450 3A subfamily A</strong>.</p>
</section>
<section id="data-and-normalization" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> Data and normalization</h1>
<p>Replicate measurements were Box-Cox transformed with a protein-specific λ = <strong>0.65</strong> (95% likelihood interval 0.53 to 0.78), estimated on the individual replicates (<code>boxcox(y ~ strain)</code>, no +1 shift). The strain phenotype is the mean of the transformed replicates and the strain noise used for the wisam weights is their variance.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/proteins/Cyp3a11_normalization.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Cyp3a11: raw replicates, Box-Cox likelihood profile and transformed replicates.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/proteins/Cyp3a11_normalization.png" download="Cyp3a11_normalization.png">PNG</a> · <a href="figures/repbc_2026-10-01/proteins/Cyp3a11_normalization.pdf" download="Cyp3a11_normalization.pdf">PDF</a></p>
</div>
<section id="heritability" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="heritability"><span class="header-section-number">18.1</span> Heritability</h2>
<p>Broad-sense heritability of the protein is <strong>0.60</strong> (95% CI 0.44–0.71; BH-adjusted P 5.35e-18). Its paired transcript is <strong>Cyp3a11</strong> (array probe <code>1416809_PM_at</code>, paired from the measured peptide <code>LYPIANR</code>). Transcript H² is <strong>0.20</strong> (95% CI 0.03–0.34; BH-adjusted P 4.89e-03).</p>
</section>
</section>
<section id="pqtl-genome-scan" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> pQTL genome scan</h1>
<p>Genome scan of the Box-Cox phenotype with wisam weights (miqtl <code>scan.h2lmm</code>, 11 imputations); significance thresholds come from 1000 permutations (GEV fit to the permutation maxima of −log10 P). Strongest locus: chr3:41.34 Mb, P = 4.65e-06, adjusted P = 2.48e-02; 95% threshold = 5.00 (−log10 P).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_genome_scan.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Cyp3a11 genome-wide pQTL scan with the permutation threshold.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_genome_scan.pdf" download="Cyp3a11_genome_scan.pdf">PDF</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_scan_by_chromosome.pdf" download="Cyp3a11_scan_by_chromosome.pdf">PDF</a></p>
</div>
</section>
<section id="significant-peaks" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> Significant peak(s)</h1>
<section id="chromosome-3-peak-unc5114998" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="chromosome-3-peak-unc5114998"><span class="header-section-number">20.1</span> Chromosome 3 peak (UNC5114998)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Peak position</th>
<th style="text-align: right;">−log10(P)</th>
<th style="text-align: right;">Adjusted P</th>
<th>90% credible interval</th>
<th>Encoding gene</th>
<th>Gene location</th>
<th>pQTL type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chr3:41.34 Mb</td>
<td style="text-align: right;">5.33</td>
<td style="text-align: right;">2.48e-02</td>
<td>38.04–104.21 Mb</td>
<td>Cyp3a11</td>
<td>chr5:145.85–145.88 Mb</td>
<td><strong>trans</strong></td>
</tr>
</tbody>
</table>
<p>A pQTL is <strong>cis</strong> when the gene encoding the protein lies within the credible interval and <strong>trans</strong> otherwise.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_scans_full_p1.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Bootstrap credible interval, chromosome 3.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_scans_full.pdf" download="Cyp3a11_ci_scans_full.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_genes_full_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Genes within the credible interval, chromosome 3 (80% interval boxed).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_genes_full_chr3.png" download="Cyp3a11_ci_genes_full_chr3.png">PNG</a></p>
</div>
<section id="merge-diplotype-fine-mapping" class="level3" data-number="20.1.1">
<h3 data-number="20.1.1" class="anchored" data-anchor-id="merge-diplotype-fine-mapping"><span class="header-section-number">20.1.1</span> Merge / diplotype fine-mapping</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mergeplot_full_UNC5114998.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Merge: SDP significance profile across the credible interval.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mergeplot_full_UNC5114998.png" download="Cyp3a11_mergeplot_full_UNC5114998.png">PNG</a></p>
</div>
<p><em>The top allelic series (SDP) from Merge is added to the book once the follow-up summary has been generated.</em></p>
</section>
<section id="timbr-allelic-series" class="level3" data-number="20.1.2">
<h3 data-number="20.1.2" class="anchored" data-anchor-id="timbr-allelic-series"><span class="header-section-number">20.1.2</span> TIMBR allelic series</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_bf_dot_chr3.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (Bayes-factor dot plot), chromosome 3; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_bf_dot_chr3.jpg" download="Cyp3a11_timbr_ci_bf_dot_chr3.jpg">JPG</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_dot_chr3.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (posterior-probability dot plot), chromosome 3; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_dot_chr3.jpg" download="Cyp3a11_timbr_ci_dot_chr3.jpg">JPG</a></p>
</div>
<p>The highest-posterior TIMBR allelic series at the peak splits the founders into <strong>allele 0</strong>: A/J, C57BL/6J, 129S1/SvImJ, WSB/EiJ; <strong>allele 1</strong>: NOD/ShiLtJ, NZO/HlLtJ, CAST/EiJ, PWK/PhJ. That is 2 functional alleles: founders in the same group are inferred to carry the same functional allele at this locus.</p>
<p><strong>Number of functional alleles.</strong> At the lead locus (UNC5114998, 41.34 Mb) the posterior probability of a bi-allelic series (two functional alleles) is 0.30, tri-allelic 0.39, and four or more alleles 0.31; a single allele (no QTL effect) has probability 0.00. For comparison, the Chinese-restaurant-process prior gives 0.50 / 0.29 / 0.14 for one / two / three alleles, so the data move weight away from a single allele. The locus in the credible interval whose single best allelic series has the highest posterior probability is UNC030147562 (94.22 Mb; series 0,0,0,0,0,0,0,0, P = 0.70); there bi-allelic = 0.20, tri-allelic = 0.07, four or more = 0.03.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_prior_posterior_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Prior (uniform over partitions and Chinese restaurant process) versus posterior probability of the number of functional alleles at the lead and best-model loci.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_prior_posterior_chr3.png" download="Cyp3a11_allele_number_prior_posterior_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_prior_posterior_chr3.pdf" download="Cyp3a11_allele_number_prior_posterior_chr3.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_across_ci_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probability of 1, 2, 3 or 4+ functional alleles at each locus across the credible interval (dashed line: lead locus; dotted line: best-model locus).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_across_ci_chr3.png" download="Cyp3a11_allele_number_across_ci_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_across_ci_chr3.pdf" download="Cyp3a11_allele_number_across_ci_chr3.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_lead_UNC5114998_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the lead locus UNC5114998.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_lead_UNC5114998_chr3.png" download="Cyp3a11_haplotype_lead_UNC5114998_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_lead_UNC5114998_chr3.pdf" download="Cyp3a11_haplotype_lead_UNC5114998_chr3.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_best_UNC030147562_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the locus with the highest-probability allelic series, UNC030147562.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_best_UNC030147562_chr3.png" download="Cyp3a11_haplotype_best_UNC030147562_chr3.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_best_UNC030147562_chr3.pdf" download="Cyp3a11_haplotype_best_UNC030147562_chr3.pdf">PDF</a></p>
</div>
</section>
<section id="rna-mediation" class="level3" data-number="20.1.3">
<h3 data-number="20.1.3" class="anchored" data-anchor-id="rna-mediation"><span class="header-section-number">20.1.3</span> RNA mediation</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_overlay_bf_chr3_nogenes.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>RNA mediation: pQTL scan (left axis) and each candidate transcript’s best-supported model, log10 Bayes factor (right axis); transcripts with a mediation or co-local best model and log10 BF of at least 0.5 are labelled.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_overlay_bf_chr3_nogenes.png" download="Cyp3a11_mediation_overlay_bf_chr3_nogenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_overlay_bf_chr3_withgenes.png" download="Cyp3a11_mediation_overlay_bf_chr3_withgenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_bf_points_chr3.csv" download="Cyp3a11_mediation_bf_points_chr3.csv">CSV</a></p>
</div>
<p>467 candidate transcripts lie in the credible interval. <strong>52</strong> have a best-model log10 Bayes factor ≥ 0.5 with mediation or co-local as the best-supported model and are labelled in the figure (377 more reach 0.5 only for the non-mediator model and are not labelled): <strong>co-local</strong> (52): Efna1 (1.84), Setd7 (1.78), Tdo2 (1.72), Ndufc1 (1.65), Tmem154 (1.59), Rap2b (1.59), Cycs (1.51), Mfsd1 (1.50), Npy (1.40), Arf5 (1.36), Lix1l (1.34), Ints3 (1.31) …. <em>Mediation</em> means the transcript is best explained as lying on the path from the QTL to the protein; <em>co-local</em> means it shares the QTL without mediating; log10 BF is the evidence for the best-supported model against the null.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Function of the 52 labelled transcripts (UniProt)">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Function of the 52 labelled transcripts (UniProt)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Function text is the UniProt (mouse) annotation retrieved on 2026-10-03; reviewed Swiss-Prot entries where available. A dash means UniProt holds no functional annotation for that symbol.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Transcript</th>
<th>Best model</th>
<th style="text-align: right;">log10 BF</th>
<th>UniProt protein</th>
<th>Function (UniProt)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Efna1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.84</td>
<td><a href="https://www.uniprot.org/uniprotkb/P52793">Ephrin-A1</a></td>
<td>Cell surface GPI-bound ligand for Eph receptors, a family of receptor tyrosine kinases which are crucial for migration, repulsion and adhesion during neuronal, vascular and epithelial development. Binds promiscuously Eph receptors residing on adjacent cells, leading to contact-dependent bidirectional signaling into neighboring cells.</td>
</tr>
<tr class="even">
<td><em>Setd7</em></td>
<td>co-local</td>
<td style="text-align: right;">1.78</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8VHL1">Histone-lysine N-methyltransferase SETD7</a></td>
<td>Histone methyltransferase that specifically monomethylates ‘Lys-4’ of histone H3. H3 ‘Lys-4’ methylation represents a specific tag for epigenetic transcriptional activation. Plays a central role in the transcriptional activation of genes such as collagenase or insulin. Recruited by IPF1/PDX-1 to the insulin promoter, leading to activate transcription.</td>
</tr>
<tr class="odd">
<td><em>Tdo2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.72</td>
<td><a href="https://www.uniprot.org/uniprotkb/P48776">Tryptophan 2,3-dioxygenase</a></td>
<td>Heme-dependent dioxygenase that catalyzes the oxidative cleavage of the L-tryptophan (L-Trp) pyrrole ring and converts L-tryptophan to N-formyl-L-kynurenine. Catalyzes the oxidative cleavage of the indole moiety</td>
</tr>
<tr class="even">
<td><em>Ndufc1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.65</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9CQY9">NADH dehydrogenase [ubiquinone] 1 subunit C1, mitochondrial</a></td>
<td>Accessory subunit of the mitochondrial membrane respiratory chain NADH dehydrogenase (Complex I), that is believed not to be involved in catalysis. Complex I functions in the transfer of electrons from NADH to the respiratory chain. The immediate electron acceptor for the enzyme is believed to be ubiquinone</td>
</tr>
<tr class="odd">
<td><em>Tmem154</em></td>
<td>co-local</td>
<td style="text-align: right;">1.59</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8C4Q9">Transmembrane protein 154</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Rap2b</em></td>
<td>co-local</td>
<td style="text-align: right;">1.59</td>
<td><a href="https://www.uniprot.org/uniprotkb/P61226">Ras-related protein Rap-2b</a></td>
<td>Small GTP-binding protein which cycles between a GDP-bound inactive and a GTP-bound active form. Involved in EGFR and CHRM3 signaling pathways through stimulation of PLCE1. May play a role in cytoskeletal rearrangements and regulate cell spreading through activation of the effector TNIK. May regulate membrane vesiculation in red blood cells</td>
</tr>
<tr class="odd">
<td><em>Cycs</em></td>
<td>co-local</td>
<td style="text-align: right;">1.51</td>
<td><a href="https://www.uniprot.org/uniprotkb/P62897">Cytochrome c, somatic</a></td>
<td>Electron carrier protein. The oxidized form of the cytochrome c heme group can accept an electron from the heme group of the cytochrome c1 subunit of cytochrome reductase. Cytochrome c then transfers this electron to the cytochrome oxidase complex, the final protein carrier in the mitochondrial electron-transport chain</td>
</tr>
<tr class="even">
<td><em>Mfsd1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.50</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DC37">Lysosomal dipeptide transporter MFSD1</a></td>
<td>Lysosomal dipeptide uniporter that selectively exports lysine, arginine or histidine-containing dipeptides with a net positive charge from the lysosome lumen into the cytosol. Could play a role in a specific type of protein O-glycosylation indirectly regulating macrophages migration and tissue invasion. Also essential for liver homeostasis</td>
</tr>
<tr class="odd">
<td><em>Npy</em></td>
<td>co-local</td>
<td style="text-align: right;">1.40</td>
<td><a href="https://www.uniprot.org/uniprotkb/P57774">Pro-neuropeptide Y</a></td>
<td>Ligand for neuropeptide Y receptor type 1 (NPY1R) and neuropeptide Y receptor type 2 (NPY2R). Receptor binding induces adenylate cyclase-inhibiting G protein-coupled receptor signaling, resulting in inhibition of cAMP production. Receptor activation by NPY also leads to an increase of intracellular Ca(2+) levels.</td>
</tr>
<tr class="even">
<td><em>Arf5</em></td>
<td>co-local</td>
<td style="text-align: right;">1.36</td>
<td><a href="https://www.uniprot.org/uniprotkb/P84084">ADP-ribosylation factor 5</a></td>
<td>GTP-binding protein involved in protein trafficking. Contributes to vesicle budding and uncoating at the Golgi apparatus. Regulates mTORC1 activity at the plasma membrane by promoting its recruitment to membrane ruffles, facilitating activation via the PI3K/Akt signaling pathway.</td>
</tr>
<tr class="odd">
<td><em>Lix1l</em></td>
<td>co-local</td>
<td style="text-align: right;">1.34</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BQ89">LIX1-like protein</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Ints3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.31</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q7TPD0">Integrator complex subunit 3</a></td>
<td>Component of the integrator complex, a multiprotein complex that terminates RNA polymerase II (Pol II) transcription in the promoter-proximal region of genes.</td>
</tr>
<tr class="odd">
<td><em>Akr1b10</em></td>
<td>co-local</td>
<td style="text-align: right;">1.30</td>
<td><a href="https://www.uniprot.org/uniprotkb/G5E895">aldose reductase</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Mgst2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.30</td>
<td><a href="https://www.uniprot.org/uniprotkb/A2RST1">Microsomal glutathione S-transferase 2</a></td>
<td>Catalyzes several different glutathione-dependent reactions. Catalyzes the glutathione-dependent reduction of lipid hydroperoxides, such as 5-HPETE. Has glutathione transferase activity, toward xenobiotic electrophiles, such as 1-chloro-2, 4-dinitrobenzene (CDNB). Also catalyzes the conjugation of leukotriene A4 with reduced glutathione to form leukotriene C4 (LTC4).</td>
</tr>
<tr class="odd">
<td><em>Acp6</em></td>
<td>co-local</td>
<td style="text-align: right;">1.28</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BP40">Lysophosphatidic acid phosphatase type 6</a></td>
<td>Hydrolyzes lysophosphatidic acid (LPA) containing a medium length fatty acid chain to the corresponding monoacylglycerol. Has highest activity with lysophosphatidic acid containing myristate (C14:0), monounsaturated oleate (C18:1) or palmitate (C16:0), and lower activity with C18:0 and C6:0 lysophosphatidic acid</td>
</tr>
<tr class="even">
<td><em>Lce3b</em></td>
<td>co-local</td>
<td style="text-align: right;">1.26</td>
<td><a href="https://www.uniprot.org/uniprotkb/F6QNI6">Late cornified envelope 3B</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Gmps</em></td>
<td>co-local</td>
<td style="text-align: right;">1.24</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q3THK7">GMP synthase [glutamine-hydrolyzing]</a></td>
<td>Catalyzes the conversion of xanthine monophosphate (XMP) to GMP in the presence of glutamine and ATP through an adenyl-XMP intermediate</td>
</tr>
<tr class="even">
<td><em>Zfp786</em></td>
<td>co-local</td>
<td style="text-align: right;">1.18</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BV42">Zinc finger protein 786</a></td>
<td>May be involved in transcriptional regulation</td>
</tr>
<tr class="odd">
<td><em>Ufm1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.18</td>
<td><a href="https://www.uniprot.org/uniprotkb/P61961">Ubiquitin-fold modifier 1</a></td>
<td>Ubiquitin-like modifier which can be covalently attached via an isopeptide bond to lysine residues of substrate proteins as a monomer or a lysine-linked polymer. The so-called ufmylation, requires the UFM1-activating E1 enzyme UBA5, the UFM1-conjugating E2 enzyme UFC1, and the UFM1-ligase E3 enzyme UFL1.</td>
</tr>
<tr class="even">
<td><em>Paqr6</em></td>
<td>co-local</td>
<td style="text-align: right;">1.11</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q6TCG5">Membrane progestin receptor delta</a></td>
<td>Plasma membrane progesterone (P4) receptor coupled to G proteins. Seems to act through a G(s) mediated pathway. Involved in neurosteroid inhibition of apoptosis. May be involved in regulating rapid P4 signaling in the nervous system. Also binds dehydroepiandrosterone (DHEA), pregnanolone, pregnenolone and allopregnanolone</td>
</tr>
<tr class="odd">
<td><em>Gria2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.11</td>
<td><a href="https://www.uniprot.org/uniprotkb/P23819">Glutamate receptor 2</a></td>
<td>Ionotropic glutamate receptor that functions as a ligand-gated cation channel, gated by L-glutamate and glutamatergic agonists such as alpha-amino-3-hydroxy-5-methyl-4-isoxazolepropionic acid (AMPA), quisqualic acid, and kainic acid.</td>
</tr>
<tr class="even">
<td><em>Tiparp</em></td>
<td>co-local</td>
<td style="text-align: right;">1.09</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8C1B2">Protein mono-ADP-ribosyltransferase TIPARP</a></td>
<td>ADP-ribosyltransferase that mediates mono-ADP-ribosylation of glutamate, aspartate and cysteine residues on target proteins. Acts as a negative regulator of AHR by mediating mono-ADP-ribosylation of AHR, leading to inhibit transcription activator activity of AHR (Probable)</td>
</tr>
<tr class="odd">
<td><em>Naa15</em></td>
<td>co-local</td>
<td style="text-align: right;">1.07</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80UM3">N-alpha-acetyltransferase 15, NatA auxiliary subunit</a></td>
<td>Auxillary subunit of N-terminal acetyltransferase complexes which display alpha (N-terminal) acetyltransferase (NAT) activity. The NAT activity may be important for vascular, hematopoietic and neuronal growth and development. Required to control retinal neovascularization in adult ocular endothelial cells.</td>
</tr>
<tr class="even">
<td><em>Clrn1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.06</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8K445">Clarin-1</a></td>
<td>May have a role in the excitatory ribbon synapse junctions between hair cells and cochlear ganglion cells and presumably also in analogous synapses within the retina</td>
</tr>
<tr class="odd">
<td><em>Pgrmc2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.05</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80UU9">Membrane-associated progesterone receptor component 2</a></td>
<td>Required for the maintenance of uterine histoarchitecture and normal female reproductive lifespan. May serve as a universal non-classical progesterone receptor in the uterus (Probable). Intracellular heme chaperone required for delivery of labile, or signaling heme, to the nucleus. Plays a role in adipocyte function and systemic glucose homeostasis.</td>
</tr>
<tr class="even">
<td><em>Arnt</em></td>
<td>co-local</td>
<td style="text-align: right;">1.04</td>
<td><a href="https://www.uniprot.org/uniprotkb/P53762">Aryl hydrocarbon receptor nuclear translocator</a></td>
<td>Transcription factor that functions as an obligate heterodimerization partner for several basic helix-loop-helix PER-ARNT-SIM (bHLH-PAS) proteins. Forms heterodimers with the aryl hydrocarbon receptor (AHR) to mediate the transcriptional response to xenobiotics by binding xenobiotic response elements (XREs) or dioxin response elements (DREs) in target gene promoters.</td>
</tr>
<tr class="odd">
<td><em>Pmvk</em></td>
<td>co-local</td>
<td style="text-align: right;">1.04</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9D1G2">Phosphomevalonate kinase</a></td>
<td>Catalyzes the reversible ATP-dependent phosphorylation of mevalonate 5-phosphate to produce mevalonate diphosphate and ADP, a key step in the mevalonic acid mediated biosynthesis of isopentenyl diphosphate and other polyisoprenoid metabolites</td>
</tr>
<tr class="even">
<td><em>Tax1bp1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.02</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q3UKC1">Tax1-binding protein 1 homolog</a></td>
<td>Ubiquitin-binding adapter that participates in inflammatory, antiviral and innate immune processes as well as selective autophagy regulation. Plays a key role in the negative regulation of NF-kappa-B and IRF3 signalings by acting as an adapter for the ubiquitin-editing enzyme A20/TNFAIP3 to bind and inactivate its substrates.</td>
</tr>
<tr class="odd">
<td><em>Efna4</em></td>
<td>co-local</td>
<td style="text-align: right;">1.01</td>
<td><a href="https://www.uniprot.org/uniprotkb/O08542">Ephrin-A4</a></td>
<td>Cell surface GPI-bound ligand for Eph receptors, a family of receptor tyrosine kinases which are crucial for migration, repulsion and adhesion during neuronal, vascular and epithelial development. Binds promiscuously Eph receptors residing on adjacent cells, leading to contact-dependent bidirectional signaling into neighboring cells.</td>
</tr>
<tr class="even">
<td><em>Lxn</em></td>
<td>co-local</td>
<td style="text-align: right;">1.00</td>
<td><a href="https://www.uniprot.org/uniprotkb/P70202">Latexin</a></td>
<td>Hardly reversible, non-competitive, and potent inhibitor of CPA1, CPA2 and CPA4. May play a role in inflammation</td>
</tr>
<tr class="odd">
<td><em>Foxo1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.95</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9R1E0">Forkhead box protein O1</a></td>
<td>Transcription factor that is the main target of insulin signaling and regulates metabolic homeostasis in response to oxidative stress. Binds to the insulin response element (IRE) with consensus sequence 5’-TT[G/A]TTTTG-3’ and the related Daf-16 family binding element (DBE) with consensus sequence 5’-TT[G/A]TTTAC-3’. Activity suppressed by insulin.</td>
</tr>
<tr class="even">
<td><em>Fga</em></td>
<td>co-local</td>
<td style="text-align: right;">0.95</td>
<td><a href="https://www.uniprot.org/uniprotkb/E9PV24">Fibrinogen alpha chain</a></td>
<td>Cleaved by the protease thrombin to yield monomers which, together with fibrinogen beta (FGB) and fibrinogen gamma (FGG), polymerize to form an insoluble fibrin matrix. Fibrin has a major function in hemostasis as one of the primary components of blood clots.</td>
</tr>
<tr class="odd">
<td><em>Intu</em></td>
<td>co-local</td>
<td style="text-align: right;">0.90</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q059U7">Protein inturned</a></td>
<td>Plays a key role in ciliogenesis and embryonic development. Regulator of cilia formation by controlling the organization of the apical actin cytoskeleton and the positioning of the basal bodies at the apical cell surface, which in turn is essential for the normal orientation of elongating ciliary microtubules.</td>
</tr>
<tr class="even">
<td><em>Ankrd50</em></td>
<td>co-local</td>
<td style="text-align: right;">0.84</td>
<td><a href="https://www.uniprot.org/uniprotkb/F6UUU0">Ankyrin repeat domain 50</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Mfsd8</em></td>
<td>co-local</td>
<td style="text-align: right;">0.83</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BH31">Major facilitator superfamily domain-containing protein 8</a></td>
<td>Outward-rectifying chloride channel involved in endolysosomal chloride homeostasis, membrane fusion and function. Conducts chloride currents up to hundreds of picoamperes. Regulates lysosomal calcium content by reducing the lysosomal membrane potential, thereby activating TRPML1 channel and further release of lysosomal calcium ions.</td>
</tr>
<tr class="even">
<td><em>Tnpo3</em></td>
<td>co-local</td>
<td style="text-align: right;">0.81</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q6P2B1">Transportin-3</a></td>
<td>Importin, which transports target proteins into the nucleus. Specifically mediates the nuclear import of splicing factor serine/arginine (SR) proteins, such as RBM4, SFRS1 and SFRS2, by recognizing phosphorylated SR domains. Also mediates the nuclear import of serine/arginine (SR) protein CPSF6, independently of CPSF6 phosphorylation.</td>
</tr>
<tr class="odd">
<td><em>Cog6</em></td>
<td>co-local</td>
<td style="text-align: right;">0.80</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8R3I3">Conserved oligomeric Golgi complex subunit 6</a></td>
<td>Required for normal Golgi function</td>
</tr>
<tr class="even">
<td><em>Copg2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.79</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9QXK3">Coatomer subunit gamma-2</a></td>
<td>The coatomer is a cytosolic protein complex that binds to dilysine motifs and reversibly associates with Golgi non-clathrin-coated vesicles, which further mediate biosynthetic protein transport from the ER, via the Golgi up to the trans Golgi network.</td>
</tr>
<tr class="odd">
<td><em>Ccnl1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.77</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q52KE7">Cyclin-L1</a></td>
<td>Regulatory component of the cyclin-L-CDK11 complex that regulates transcription and pre-mRNA splicing. Inhibited by the CDK-specific inhibitor CDKN1A/p21</td>
</tr>
<tr class="even">
<td><em>Akr1d1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.76</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8VCX1">Aldo-keto reductase family 1 member D1</a></td>
<td>Catalyzes the stereospecific NADPH-dependent reduction of the C4-C5 double bond of bile acid intermediates and steroid hormones carrying a delta(4)-3-one structure to yield an A/B cis-ring junction. This cis-configuration is crucial for bile acid biosynthesis and plays important roles in steroid metabolism.</td>
</tr>
<tr class="odd">
<td><em>S100a10</em></td>
<td>co-local</td>
<td style="text-align: right;">0.74</td>
<td><a href="https://www.uniprot.org/uniprotkb/P08207">Protein S100-A10</a></td>
<td>Because S100A10 induces the dimerization of ANXA2/p36, it may function as a regulator of protein phosphorylation in that the ANXA2 monomer is the preferred target (in vitro) of tyrosine-specific kinase</td>
</tr>
<tr class="even">
<td><em>Zfp697</em></td>
<td>co-local</td>
<td style="text-align: right;">0.74</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q569E7">Zinc finger protein 697</a></td>
<td>RNA-interacting protein with a high number of miRNA targets. Acts as a damage-induced regulator of muscle remodeling by mediating the interferon gamma response in muscle cells</td>
</tr>
<tr class="odd">
<td><em>Tbxas1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.73</td>
<td><a href="https://www.uniprot.org/uniprotkb/P36423">Thromboxane-A synthase</a></td>
<td>Catalyzes the conversion of prostaglandin H2 (PGH2) to thromboxane A2 (TXA2), a potent inducer of blood vessel constriction and platelet aggregation. Also cleaves PGH2 to 12-hydroxy-heptadecatrienoicacid (12-HHT) and malondialdehyde, which is known to act as a mediator of DNA damage. 12-HHT and malondialdehyde are formed stoichiometrically in the same amounts as TXA2.</td>
</tr>
<tr class="even">
<td><em>Vangl1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.69</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80Z96">Vang-like protein 1</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Rapgef2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.68</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8CHG7">Rap guanine nucleotide exchange factor 2</a></td>
<td>Functions as a guanine nucleotide exchange factor (GEF), which activates Rap and Ras family of small GTPases by exchanging bound GDP for free GTP in a cAMP-dependent manner. Serves as a link between cell surface receptors and Rap/Ras GTPases in intracellular signaling cascades.</td>
</tr>
<tr class="even">
<td><em>She</em></td>
<td>co-local</td>
<td style="text-align: right;">0.66</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BSD5">SH2 domain-containing adapter protein E</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Pdia4</em></td>
<td>co-local</td>
<td style="text-align: right;">0.63</td>
<td><a href="https://www.uniprot.org/uniprotkb/P08003">Protein disulfide-isomerase A4</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>P2ry1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.60</td>
<td><a href="https://www.uniprot.org/uniprotkb/P49650">P2Y purinoceptor 1</a></td>
<td>Receptor for extracellular adenine nucleotides such as ADP. In platelets, binding to ADP leads to mobilization of intracellular calcium ions via activation of phospholipase C, a change in platelet shape, and ultimately platelet aggregation</td>
</tr>
<tr class="odd">
<td><em>Vps45</em></td>
<td>co-local</td>
<td style="text-align: right;">0.59</td>
<td><a href="https://www.uniprot.org/uniprotkb/P97390">Vacuolar protein sorting-associated protein 45</a></td>
<td>May play a role in vesicle-mediated protein trafficking from the Golgi stack through the trans-Golgi network</td>
</tr>
<tr class="even">
<td><em>Opn1sw</em></td>
<td>co-local</td>
<td style="text-align: right;">0.59</td>
<td><a href="https://www.uniprot.org/uniprotkb/P51491">Short-wave-sensitive opsin 1</a></td>
<td>G protein-coupled photoreceptor that selectively activates transducin G alpha protein (G(t)) in response to short-wavelength (blue-violet) light, thereby stimulating the G(t)/transducin protein pathway. This activation leads to increased cGMP phosphodiesterase activity, resulting in decreased intracellular cGMP and subsequent closure of cGMP-gated ion channels.</td>
</tr>
<tr class="odd">
<td><em>Glt28d2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.56</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BML3">UDP-N-acetylglucosamine transferase subunit ALG13</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Gon4l</em></td>
<td>co-local</td>
<td style="text-align: right;">0.52</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DB00">GON-4-like protein</a></td>
<td>Acts as a key transcription regulator of histones. Activates transcription of the histone H2A, histone H2B, histone H3 and histone H4 genes in conjunction with GON4L and MIZF. Together with CRAMP1, binds to the promoters of H1 genes (H1-2, H1-3, H1-4, H1-5 and H1-10/H1x), driving their transcription.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_posterior_bars_chr3.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probabilities of the mediation models for the strongest candidate mediator.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_targeted_mediation_chr3_posterior_bars.pdf" download="Cyp3a11_targeted_mediation_chr3_posterior_bars.pdf">PDF</a></p>
</div>
</section>
</section>
<section id="chromosome-6-peak-unc11092470" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="chromosome-6-peak-unc11092470"><span class="header-section-number">20.2</span> Chromosome 6 peak (UNC11092470)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Peak position</th>
<th style="text-align: right;">−log10(P)</th>
<th style="text-align: right;">Adjusted P</th>
<th>90% credible interval</th>
<th>Encoding gene</th>
<th>Gene location</th>
<th>pQTL type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chr6:52.95 Mb</td>
<td style="text-align: right;">5.30</td>
<td style="text-align: right;">2.67e-02</td>
<td>18.04–64.62 Mb</td>
<td>Cyp3a11</td>
<td>chr5:145.85–145.88 Mb</td>
<td><strong>trans</strong></td>
</tr>
</tbody>
</table>
<p>A pQTL is <strong>cis</strong> when the gene encoding the protein lies within the credible interval and <strong>trans</strong> otherwise.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_scans_full_p2.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Bootstrap credible interval, chromosome 6.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_scans_full.pdf" download="Cyp3a11_ci_scans_full.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_genes_full_chr6.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Genes within the credible interval, chromosome 6 (80% interval boxed).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_ci_genes_full_chr6.png" download="Cyp3a11_ci_genes_full_chr6.png">PNG</a></p>
</div>
<section id="merge-diplotype-fine-mapping-1" class="level3" data-number="20.2.1">
<h3 data-number="20.2.1" class="anchored" data-anchor-id="merge-diplotype-fine-mapping-1"><span class="header-section-number">20.2.1</span> Merge / diplotype fine-mapping</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mergeplot_full_UNC11092470.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Merge: SDP significance profile across the credible interval.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mergeplot_full_UNC11092470.png" download="Cyp3a11_mergeplot_full_UNC11092470.png">PNG</a></p>
</div>
<p><em>The top allelic series (SDP) from Merge is added to the book once the follow-up summary has been generated.</em></p>
</section>
<section id="timbr-allelic-series-1" class="level3" data-number="20.2.2">
<h3 data-number="20.2.2" class="anchored" data-anchor-id="timbr-allelic-series-1"><span class="header-section-number">20.2.2</span> TIMBR allelic series</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_bf_dot_chr6.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (Bayes-factor dot plot), chromosome 6; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_bf_dot_chr6.jpg" download="Cyp3a11_timbr_ci_bf_dot_chr6.jpg">JPG</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_dot_chr6.jpg" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR allelic-series sweep across the credible interval (posterior-probability dot plot), chromosome 6; Merge SDP profile overlaid where available.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_timbr_ci_dot_chr6.jpg" download="Cyp3a11_timbr_ci_dot_chr6.jpg">JPG</a></p>
</div>
<p>The highest-posterior TIMBR allelic series at the peak splits the founders into <strong>allele 1</strong>: C57BL/6J, 129S1/SvImJ, NOD/ShiLtJ, NZO/HlLtJ, CAST/EiJ, PWK/PhJ, WSB/EiJ; <strong>allele 0</strong>: A/J. That is 2 functional alleles: founders in the same group are inferred to carry the same functional allele at this locus.</p>
<p><strong>Number of functional alleles.</strong> At the lead locus (UNC11092470, 52.95 Mb) the posterior probability of a bi-allelic series (two functional alleles) is 0.38, tri-allelic 0.39, and four or more alleles 0.23; a single allele (no QTL effect) has probability 0.00. For comparison, the Chinese-restaurant-process prior gives 0.50 / 0.29 / 0.14 for one / two / three alleles, so the data move weight away from a single allele. The locus in the credible interval whose single best allelic series has the highest posterior probability is JAX00605159 (24.54 Mb; series 0,0,0,0,0,0,0,0, P = 0.80); there bi-allelic = 0.14, tri-allelic = 0.04, four or more = 0.02.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_prior_posterior_chr6.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Prior (uniform over partitions and Chinese restaurant process) versus posterior probability of the number of functional alleles at the lead and best-model loci.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_prior_posterior_chr6.png" download="Cyp3a11_allele_number_prior_posterior_chr6.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_prior_posterior_chr6.pdf" download="Cyp3a11_allele_number_prior_posterior_chr6.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_across_ci_chr6.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probability of 1, 2, 3 or 4+ functional alleles at each locus across the credible interval (dashed line: lead locus; dotted line: best-model locus).</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_across_ci_chr6.png" download="Cyp3a11_allele_number_across_ci_chr6.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_allele_number_across_ci_chr6.pdf" download="Cyp3a11_allele_number_across_ci_chr6.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_lead_UNC11092470_chr6.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the lead locus UNC11092470.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_lead_UNC11092470_chr6.png" download="Cyp3a11_haplotype_lead_UNC11092470_chr6.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_lead_UNC11092470_chr6.pdf" download="Cyp3a11_haplotype_lead_UNC11092470_chr6.pdf">PDF</a></p>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_best_JAX00605159_chr6.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>TIMBR founder-haplotype effects at the locus with the highest-probability allelic series, JAX00605159.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_best_JAX00605159_chr6.png" download="Cyp3a11_haplotype_best_JAX00605159_chr6.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_haplotype_best_JAX00605159_chr6.pdf" download="Cyp3a11_haplotype_best_JAX00605159_chr6.pdf">PDF</a></p>
</div>
</section>
<section id="rna-mediation-1" class="level3" data-number="20.2.3">
<h3 data-number="20.2.3" class="anchored" data-anchor-id="rna-mediation-1"><span class="header-section-number">20.2.3</span> RNA mediation</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_overlay_bf_chr6_nogenes.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>RNA mediation: pQTL scan (left axis) and each candidate transcript’s best-supported model, log10 Bayes factor (right axis); transcripts with a mediation or co-local best model and log10 BF of at least 0.5 are labelled.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_overlay_bf_chr6_nogenes.png" download="Cyp3a11_mediation_overlay_bf_chr6_nogenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_overlay_bf_chr6_withgenes.png" download="Cyp3a11_mediation_overlay_bf_chr6_withgenes.png">PNG</a> · <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_bf_points_chr6.csv" download="Cyp3a11_mediation_bf_points_chr6.csv">CSV</a></p>
</div>
<p>467 candidate transcripts lie in the credible interval. <strong>48</strong> have a best-model log10 Bayes factor ≥ 0.5 with mediation or co-local as the best-supported model and are labelled in the figure (394 more reach 0.5 only for the non-mediator model and are not labelled): <strong>mediation</strong> (1): Tcaf1 (0.94); <strong>co-local</strong> (47): Ccdc126 (1.70), Cycs (1.68), Wipf3 (1.67), Zfp467 (1.66), Chchd3 (1.65), Lrrc61 (1.57), Wdr91 (1.56), Snapin (1.55), Gimap9 (1.53), Repin1 (1.50), Chn2 (1.45), Arhgef5 (1.40) …. <em>Mediation</em> means the transcript is best explained as lying on the path from the QTL to the protein; <em>co-local</em> means it shares the QTL without mediating; log10 BF is the evidence for the best-supported model against the null.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Function of the 48 labelled transcripts (UniProt)">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Function of the 48 labelled transcripts (UniProt)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Function text is the UniProt (mouse) annotation retrieved on 2026-10-03; reviewed Swiss-Prot entries where available. A dash means UniProt holds no functional annotation for that symbol.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Transcript</th>
<th>Best model</th>
<th style="text-align: right;">log10 BF</th>
<th>UniProt protein</th>
<th>Function (UniProt)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Tcaf1</em></td>
<td>mediation</td>
<td style="text-align: right;">0.94</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BNE1">TRPM8 channel-associated factor 1</a></td>
<td>Positively regulates the plasma membrane cation channel TRPM8 activity. Involved in the recruitment of TRPM8 to the cell surface. Promotes prostate cancer cell migration inhibition in a TRPM8-dependent manner</td>
</tr>
<tr class="even">
<td><em>Ccdc126</em></td>
<td>co-local</td>
<td style="text-align: right;">1.70</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BIS8">Coiled-coil domain-containing protein 126</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Cycs</em></td>
<td>co-local</td>
<td style="text-align: right;">1.68</td>
<td><a href="https://www.uniprot.org/uniprotkb/P62897">Cytochrome c, somatic</a></td>
<td>Electron carrier protein. The oxidized form of the cytochrome c heme group can accept an electron from the heme group of the cytochrome c1 subunit of cytochrome reductase. Cytochrome c then transfers this electron to the cytochrome oxidase complex, the final protein carrier in the mitochondrial electron-transport chain</td>
</tr>
<tr class="even">
<td><em>Wipf3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.67</td>
<td><a href="https://www.uniprot.org/uniprotkb/P0C7L0">WAS/WASL-interacting protein family member 3</a></td>
<td>May be a regulator of cytoskeletal organization (Potential). May have a role in spermatogenesis</td>
</tr>
<tr class="odd">
<td><em>Zfp467</em></td>
<td>co-local</td>
<td style="text-align: right;">1.66</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8JZL0">Zinc finger protein 467</a></td>
<td>Transcription factor that promotes adipocyte differentiation and suppresses osteoblast differentiation in the bone marrow. Enhances the osteoclast-supporting ability of stromal cells. Binds with STAT3 the consensus sequence 5’-CTTCTGGGAAGA-3’ of the acute phase response element (APRE). Transactivates several promoters including FOS, OSM and PPARG.</td>
</tr>
<tr class="even">
<td><em>Chchd3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.65</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9CRB9">MICOS complex subunit Mic19</a></td>
<td>Component of the MICOS complex, a large protein complex of the mitochondrial inner membrane that plays crucial roles in the maintenance of crista junctions, inner membrane architecture, and formation of contact sites to the outer membrane. Has also been shown to function as a transcription factor which binds to the BAG1 promoter and represses BAG1 transcription.</td>
</tr>
<tr class="odd">
<td><em>Lrrc61</em></td>
<td>co-local</td>
<td style="text-align: right;">1.57</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8R2R5">Leucine-rich repeat-containing protein 61</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Wdr91</em></td>
<td>co-local</td>
<td style="text-align: right;">1.56</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q7TMQ7">WD repeat-containing protein 91</a></td>
<td>Functions as a negative regulator of the PI3 kinase/PI3K activity associated with endosomal membranes via BECN1, a core subunit of the PI3K complex. By modifying the phosphatidylinositol 3-phosphate/PtdInsP3 content of endosomal membranes may regulate endosome fusion, recycling, sorting and early to late endosome transport.</td>
</tr>
<tr class="odd">
<td><em>Snapin</em></td>
<td>co-local</td>
<td style="text-align: right;">1.55</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9Z266">SNARE-associated protein Snapin</a></td>
<td>Component of the BLOC-1 complex, a complex that is required for normal biogenesis of lysosome-related organelles (LRO), such as platelet dense granules and melanosomes. In concert with the AP-3 complex, the BLOC-1 complex is required to target membrane protein cargos into vesicles assembled at cell bodies for delivery into neurites and nerve terminals.</td>
</tr>
<tr class="even">
<td><em>Gimap9</em></td>
<td>co-local</td>
<td style="text-align: right;">1.53</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BYB6">AIG1-type G domain-containing protein</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Repin1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.50</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q5U4E2">DNA-binding protein REPIN1</a></td>
<td>Sequence-specific double-stranded DNA-binding protein. Binds ATT-rich and T-rich DNA sequences and facilitates DNA bending. May regulate the expression of genes involved in cellular fatty acid import, including SCARB1/CD36, and genes involved in lipid droplet formation. May regulate the expression of LCN2, and thereby influence iron metabolism and apoptosis-related pathways.</td>
</tr>
<tr class="even">
<td><em>Chn2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.45</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80XD1">Beta-chimaerin</a></td>
<td>GTPase-activating protein for p21-rac</td>
</tr>
<tr class="odd">
<td><em>Arhgef5</em></td>
<td>co-local</td>
<td style="text-align: right;">1.40</td>
<td><a href="https://www.uniprot.org/uniprotkb/E9Q7D5">Rho guanine nucleotide exchange factor 5</a></td>
<td>Guanine nucleotide exchange factor which activates Rho GTPases. Strongly activates RHOA. Also strongly activates RHOB, weakly activates RHOC and RHOG and shows no effect on RHOD, RHOV, RHOQ or RAC1. Involved in regulation of cell shape and actin cytoskeletal organization.</td>
</tr>
<tr class="even">
<td><em>Vopp1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.31</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8R1C3">WW domain binding protein VOPP1</a></td>
<td>Increases the transcriptional activity of NFKB1 by facilitating its nuclear translocation, DNA-binding and associated apoptotic response, when overexpressed. May sequester WWOX in lysosomal vesicles and thereby regulate WWOX role as tumor suppressor</td>
</tr>
<tr class="odd">
<td><em>Pot1a</em></td>
<td>co-local</td>
<td style="text-align: right;">1.26</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q91WC1">Protection of telomeres protein 1</a></td>
<td>Component of the telomerase ribonucleoprotein (RNP) complex that is essential for the replication of chromosome termini. Is a component of the double-stranded telomeric DNA-binding TRF1 complex which is involved in the regulation of telomere length by cis-inhibition of telomerase.</td>
</tr>
<tr class="even">
<td><em>Inmt</em></td>
<td>co-local</td>
<td style="text-align: right;">1.25</td>
<td><a href="https://www.uniprot.org/uniprotkb/P40936">Indolethylamine N-methyltransferase</a></td>
<td>Catalyzes the N-methylation of tryptamine and structurally related compounds. Functions as a thioether S-methyltransferase and is active with a variety of thioethers and the corresponding selenium and tellurium compounds, including 3-methylthiopropionaldehyde, dimethyl selenide, dimethyl telluride, 2-methylthioethylamine, 2-methylthioethanol, methyl-n-propyl sulfide and …</td>
</tr>
<tr class="odd">
<td><em>Gimap6</em></td>
<td>co-local</td>
<td style="text-align: right;">1.23</td>
<td><a href="https://www.uniprot.org/uniprotkb/A0A0N4SW08">GTPase, IMAP family member 6</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Impdh1</em></td>
<td>co-local</td>
<td style="text-align: right;">1.21</td>
<td><a href="https://www.uniprot.org/uniprotkb/P50096">Inosine-5’-monophosphate dehydrogenase 1</a></td>
<td>Catalyzes the conversion of inosine 5’-phosphate (IMP) to xanthosine 5’-phosphate (XMP), the first committed and rate-limiting step in the de novo synthesis of guanine nucleotides, and therefore plays an important role in the regulation of cell growth. Could also have a single-stranded nucleic acid-binding activity and could play a role in RNA and/or DNA metabolism.</td>
</tr>
<tr class="odd">
<td><em>Plekha8</em></td>
<td>co-local</td>
<td style="text-align: right;">1.21</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80W71">Pleckstrin homology domain-containing family A member 8</a></td>
<td>Mediates the non-vesicular transport of glucosylceramide (GlcCer) from the trans-Golgi network (TGN) to the plasma membrane, playing a pivotal role in the synthesis of complex glycosphingolipids; binding of both phosphatidylinositol 4-phosphate (PIP) and ARF1 are essential for this GlcCer transfer ability.</td>
</tr>
<tr class="even">
<td><em>Lce1h</em></td>
<td>co-local</td>
<td style="text-align: right;">1.13</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9D7A2">Uncharacterized protein</a></td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Osbpl3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.12</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DBS9">Oxysterol-binding protein-related protein 3</a></td>
<td>Lipid transfer protein that mediates the non-vesicular transport of phosphoinositide 4-phosphate (1,2-diacyl-sn-glycero-3-phospho-(1D-myo-inositol 4-phosphate), or PI(4)P) at the plasma membrane (PM)/ endoplasmic reticulum (ER) contact sites. Extracts PI4P from the PM, in exchange for phosphatidylcholine.</td>
</tr>
<tr class="even">
<td><em>Grm8</em></td>
<td>co-local</td>
<td style="text-align: right;">1.10</td>
<td><a href="https://www.uniprot.org/uniprotkb/P47743">Metabotropic glutamate receptor 8</a></td>
<td>G protein-coupled receptor for glutamate. Ligand binding causes a conformation change that triggers signaling via guanine nucleotide-binding proteins (G proteins) and modulates the activity of down-stream effectors. Signaling inhibits adenylate cyclase activity</td>
</tr>
<tr class="odd">
<td><em>Mrpl9</em></td>
<td>co-local</td>
<td style="text-align: right;">1.07</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q99N94">Large ribosomal subunit protein bL9m</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Slc37a3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.04</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q3TIT8">Sugar phosphate exchanger 3</a></td>
<td>Unlike the other SLC37 members, lacks glucose-6-phosphate antiporter activity. In osteoclasts, forms a transporter complex with ATRAID for nitrogen-containing-bisphosphonates (N-BPs) required for releasing N-BP molecules that have trafficked to lysosomes through fluid-phase endocytosis into the cytosol</td>
</tr>
<tr class="odd">
<td><em>Itga10</em></td>
<td>co-local</td>
<td style="text-align: right;">1.00</td>
<td><a href="https://www.uniprot.org/uniprotkb/E9Q6R1">Integrin, alpha 10</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Rarres2</em></td>
<td>co-local</td>
<td style="text-align: right;">1.00</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9DD06">Retinoic acid receptor responder protein 2</a></td>
<td>Adipocyte-secreted protein (adipokine) that regulates adipogenesis, metabolism and inflammation through activation of the chemokine-like receptor 1 (CMKLR1). Also acts as a ligand for CMKLR2. Can also bind to C-C chemokine receptor-like 2 (CCRL2), but with a lower affinity than it does to CMKLR1 or CMKLR2.</td>
</tr>
<tr class="odd">
<td><em>Gprin3</em></td>
<td>co-local</td>
<td style="text-align: right;">1.00</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Fkbp14</em></td>
<td>co-local</td>
<td style="text-align: right;">0.98</td>
<td><a href="https://www.uniprot.org/uniprotkb/P59024">Peptidyl-prolyl cis-trans isomerase FKBP14</a></td>
<td>PPIase which accelerates the folding of proteins during protein synthesis. Has a preference for substrates containing 4-hydroxylproline modifications, including type III collagen. May also target type VI and type X collagens</td>
</tr>
<tr class="odd">
<td><em>Gstk1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.96</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Snx10</em></td>
<td>co-local</td>
<td style="text-align: right;">0.93</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9CWT3">Sorting nexin-10</a></td>
<td>Probable phosphoinositide-binding protein involved in protein sorting and membrane trafficking in endosomes. Plays a role in cilium biogenesis through regulation of the transport and the localization of proteins to the cilium. Required for the localization to the cilium of V-ATPase subunit ATP6V1D and ATP6V0D1, and RAB8A.</td>
</tr>
<tr class="odd">
<td><em>Npy</em></td>
<td>co-local</td>
<td style="text-align: right;">0.93</td>
<td><a href="https://www.uniprot.org/uniprotkb/P57774">Pro-neuropeptide Y</a></td>
<td>Ligand for neuropeptide Y receptor type 1 (NPY1R) and neuropeptide Y receptor type 2 (NPY2R). Receptor binding induces adenylate cyclase-inhibiting G protein-coupled receptor signaling, resulting in inhibition of cAMP production. Receptor activation by NPY also leads to an increase of intracellular Ca(2+) levels.</td>
</tr>
<tr class="even">
<td><em>Anp32e</em></td>
<td>co-local</td>
<td style="text-align: right;">0.93</td>
<td><a href="https://www.uniprot.org/uniprotkb/P97822">Acidic leucine-rich nuclear phosphoprotein 32 family member E</a></td>
<td>Histone chaperone that specifically mediates the genome-wide removal of histone H2A.Z/H2AZ1 from the nucleosome: removes H2A.Z/H2AZ1 from its normal sites of deposition, especially from enhancer and insulator regions. Not involved in deposition of H2A.Z/H2AZ1 in the nucleosome.</td>
</tr>
<tr class="odd">
<td><em>Mllt11</em></td>
<td>co-local</td>
<td style="text-align: right;">0.90</td>
<td><a href="https://www.uniprot.org/uniprotkb/P97783">Protein AF1q</a></td>
<td>Cofactor for the transcription factor TCF7. Involved in regulation of lymphoid development by driving multipotent hematopoietic progenitor cells towards a T-cell fate</td>
</tr>
<tr class="even">
<td><em>Epha1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.88</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q60750">Ephrin type-A receptor 1</a></td>
<td>Receptor tyrosine kinase which binds promiscuously membrane-bound ephrin-A family ligands residing on adjacent cells, leading to contact-dependent bidirectional signaling into neighboring cells. The signaling pathway downstream of the receptor is referred to as forward signaling while the signaling pathway downstream of the ephrin ligand is referred to as reverse signaling.</td>
</tr>
<tr class="odd">
<td><em>Jtb</em></td>
<td>co-local</td>
<td style="text-align: right;">0.88</td>
<td><a href="https://www.uniprot.org/uniprotkb/O88824">Protein JTB</a></td>
<td>Required for normal cytokinesis during mitosis. Plays a role in the regulation of cell proliferation. May be a component of the chromosomal passenger complex (CPC), a complex that acts as a key regulator of mitosis.</td>
</tr>
<tr class="even">
<td><em>Pfn2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.83</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9JJV2">Profilin-2</a></td>
<td>Binds to actin and affects the structure of the cytoskeleton. At high concentrations, profilin prevents the polymerization of actin, whereas it enhances it at low concentrations. By binding to PIP2, it inhibits the formation of IP3 and DG</td>
</tr>
<tr class="odd">
<td><em>Ghrhr</em></td>
<td>co-local</td>
<td style="text-align: right;">0.82</td>
<td><a href="https://www.uniprot.org/uniprotkb/A0A0N4SVS4">Growth hormone-releasing hormone receptor</a></td>
<td>Receptor for GRF, coupled to G proteins which activate adenylyl cyclase. Stimulates somatotroph cell growth, growth hormone gene transcription and growth hormone secretion</td>
</tr>
<tr class="even">
<td><em>Zfp777</em></td>
<td>co-local</td>
<td style="text-align: right;">0.81</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>Rps27</em></td>
<td>co-local</td>
<td style="text-align: right;">0.81</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q6ZWU9">Small ribosomal subunit protein eS27</a></td>
<td>Component of the small ribosomal subunit. The ribosome is a large ribonucleoprotein complex responsible for the synthesis of proteins in the cell. Required for proper rRNA processing and maturation of 18S rRNAs. Part of the small subunit (SSU) processome, first precursor of the small eukaryotic ribosomal subunit.</td>
</tr>
<tr class="even">
<td><em>Tmem176b</em></td>
<td>co-local</td>
<td style="text-align: right;">0.79</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9R1Q6">Transmembrane protein 176B</a></td>
<td>May play a role in the process of maturation of dendritic cells. Required for the development of cerebellar granule cells</td>
</tr>
<tr class="odd">
<td><em>Lce1i</em></td>
<td>co-local</td>
<td style="text-align: right;">0.79</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q9D7A2">Uncharacterized protein</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Aqp1</em></td>
<td>co-local</td>
<td style="text-align: right;">0.73</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q02013">Aquaporin-1</a></td>
<td>Forms a water channel that facilitates the transport of water across cell membranes, playing a crucial role in water homeostasis in various tissues. Could also be permeable to small solutes including hydrogen peroxide, glycerol and gases such as amonnia (NH3), nitric oxide (NO) and carbon dioxide (CO2).</td>
</tr>
<tr class="odd">
<td><em>Hcn3</em></td>
<td>co-local</td>
<td style="text-align: right;">0.62</td>
<td><a href="https://www.uniprot.org/uniprotkb/O88705">Potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 3</a></td>
<td>Hyperpolarization-activated ion channel that are permeable to sodium and potassium ions, with an about 3:1 preference for potassium ions. Contributes to the native pacemaker currents in heart (If) and in neurons (Ih). In particular, plays a pivotal role in maintaining excitability and promoting rhythmic burst firing within hypothalamic nuclei.</td>
</tr>
<tr class="even">
<td><em>Adamtsl4</em></td>
<td>co-local</td>
<td style="text-align: right;">0.56</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q80T21">ADAMTS-like protein 4</a></td>
<td>Positive regulation of apoptosis. May facilitate FBN1 microfibril biogenesis</td>
</tr>
<tr class="odd">
<td><em>Mex3a</em></td>
<td>co-local</td>
<td style="text-align: right;">0.54</td>
<td><a href="https://www.uniprot.org/uniprotkb/G3UYU0">Mex3 RNA binding family member A</a></td>
<td>—</td>
</tr>
<tr class="even">
<td><em>Cd1d2</em></td>
<td>co-local</td>
<td style="text-align: right;">0.52</td>
<td><a href="https://www.uniprot.org/uniprotkb/P11610">Antigen-presenting glycoprotein CD1d2</a></td>
<td>Antigen-presenting protein that binds self and non-self glycolipids and presents them to T-cell receptors on natural killer T-cells</td>
</tr>
<tr class="odd">
<td><em>Zfp775</em></td>
<td>co-local</td>
<td style="text-align: right;">0.52</td>
<td><a href="https://www.uniprot.org/uniprotkb/Q8BI73">Zinc finger protein 775</a></td>
<td>May be involved in transcriptional regulation</td>
</tr>
<tr class="even">
<td><em>4930579G24Rik</em></td>
<td>co-local</td>
<td style="text-align: right;">0.52</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_mediation_posterior_bars_chr6.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Posterior probabilities of the mediation models for the strongest candidate mediator.</figcaption>
</figure>
</div>
<div class="fig-downloads">
<p>Download: <a href="figures/repbc_2026-10-01/per_protein/Cyp3a11/Cyp3a11_targeted_mediation_chr6_posterior_bars.pdf" download="Cyp3a11_targeted_mediation_chr6_posterior_bars.pdf">PDF</a></p>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Cyp2f2.html" class="pagination-link" aria-label="Cyp2f2">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cyp2f2</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ent1.html" class="pagination-link" aria-label="Ent1">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ent1</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>